### ISSUE TITLE
Move comparison with Kalman filter methods for CARMA models to a separate section?

### ISSUE THREAD

**Issue by dfm** [dfm/celerite#100]
A lot of people are interested in the comparison to CARMA methods and they are familiar to some astronomers, so it might be worth expanding this discussion.

**Comment by ericagol** [comment]
The referee also mentioned the Kalman filter, which this paper shows is related to Cholesky decomposition, which may be worth mentioning when we describe Siva's new technique:

https://www.jstor.org/stable/3087325
