### ISSUE TITLE
Description of Choleksy solver technique

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#102]
The new section on the Cholesky solver technique looks great!  A couple of ideas/questions:

1).  Should we describe how the vectors change when we have a mixture of complex and real components?

2).  Add equations for simulation:  y = L sqrt(D) {\cal N}(0,I)  (i.e. a vector of N normal deviates with mean zero & covariance of the identity matrix).

3).  Add in description of prediction in O(N J^2).

**Comment by dfm** [comment]
I've moved this to #96 to consolidate.
