### ISSUE TITLE
Automatically generated PDF is missing pages

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#117]
It's missing pages 11-12.

**Comment by ericagol** [comment]
Actually, they're just out of order.

**Comment by dfm** [comment]
Are you sure? It looks fine to me.

**Comment by ericagol** [comment]
Pages 11-12 come between 15-16 in the master-pdf

**Comment by dfm** [comment]
Not on my computer. I just refreshed and downloaded it and I'm not finding that.

**Comment by dfm** [comment]
@ericagol: any update on this? I'm still not seeing any issue, but maybe I'm missing something.

**Comment by ericagol** [comment]
Yes, it's still happening when I view ms.pdf in the github browser.  When I download the file, it's fine!  So, no big deal.

**Comment by dfm** [comment]
Strange. I feel like that must have something to do with your browser since it's working over here, but it's pretty surprising!

I'm going to close this but we can revisit if it remains an issue.
