### ISSUE TITLE
Rank vs. J

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#119]
Some equations should use R for rank rather than J (or 2J).

**Comment by dfm** [comment]
That's right. I have the full general derivation with R then I introduce
the celerite semiseparable form as a special form.

**Comment by dfm** [comment]
@ericagol: Is this a problem?

**Comment by ericagol** [comment]
This was mainly a note for myself to revisit some of the appendix equations, like B24, B28 & B41, to see whether the limits of the sums are correct only for all complex terms, or should be generalized for real + complex terms.

**Comment by dfm** [comment]
Got it.

**Comment by dfm** [comment]
I think we're good on this one now.
