### ISSUE TITLE
Faster dot_solve

### ISSUE THREAD

**Issue by dfm** [dfm/celerite#122]
See ericagol/celerite.jl#22

**Comment by dfm** [comment]
@ericagol: I did this and I got a speed up of more than the expected factor of ~2 in the likelihood calculation (no change in the factorization, obviously) because it also reduces the memory allocation requirements substantially.

**Comment by ericagol** [comment]
Nice!

Eric Agol
Astronomy Professor
University of Washington

**Comment by ericagol** [comment]
@dfm Should we mention this in the paper?

**Comment by dfm** [comment]
I'm not sure that it really adds enough to be worth it - it's just an implementation detail. An interesting fact to know though!
