### ISSUE TITLE
Jitter Parameter is Actually `log(sigma^2)`?

### ISSUE THREAD

**Issue by farr** [dfm/celerite#123]
I was just doing some exploratory analysis with a `JitterTerm` in the Celerite kernel, and I seemed to be getting good fits only when the parameter to this term was `log(sigma*sigma)`, where `sigma` is ~ data standard deviation.  I had a quick look at the code, but I couldn't determine with confidence whether this was really the case (exploratory == I don't know how well-constrained the jitter term should be).  Are you sure that the jitter parameter is `log(sigma)`?

**Comment by dfm** [comment]
Hi Will, The parameter should definitely be `log(sigma)` but the `get_jitter` method returns `exp(2*log_sigma)` here's where it gets squared in the code: https://github.com/dfm/celerite/blob/master/celerite/terms.py#L356

**Comment by farr** [comment]
Nevermind.  The data I was fitting with the Jitter term (residuals after subtracting a correlated model) were *most definitely* not even *close* to white, so the fits essentially went off the rails and confused me.  Sorry for the false alarm!

**Comment by dfm** [comment]
Cool. Thanks for the update!
