### ISSUE TITLE
common kernel components in Python

### ISSUE THREAD

**Issue by JohannesBuchner** [dfm/celerite#124]
george provides nice shortcuts for common kernels - http://dan.iel.fm/george/current/user/kernels/
I was hoping that something similar could be made available for celerite, or at least an example how to make e.g. a ExpSine2Kernel using the modelling language from its components.

**Comment by dfm** [comment]
Thanks for the suggestions but this isn't/won't ever be natively supported by celerite. As discussed in the paper, the fast algorithm requires a specific form of kernel and these other kernels do not fall into that category. While it is possible to approximate these kernels (under some definition of approximate), the properties of the approximation (number of derivatives, continuity, etc.) won't, in general, be the same. Furthermore, unless you have a physically motivated reason to use the `ExpSine2Kernel`, I'm confident that it's possible to construct a celerite term that has the properties that you want. I'd be happy to consult on specifics if you have something in mind, but let's switch to email for that - my address isn't hard to find!
