### ISSUE TITLE
Julia tutorial out-of-date

### ISSUE THREAD

**Issue by giordano** [dfm/celerite#129]
The notebook for the Julia tutorial (`docs/_static/notebooks/julia-first.ipynb`) doesn't work with the current version of `celerite.jl`.  Function `celerite.predict` doesn't exist anymore, it has been replaced by `celerite.predict_full` or `celerite.predict_full_ldlt`.  Even with either of these changes, the test `@assert(length(y)==N)` in `apply_inverse{,_ldlt}` fails throwing an error.  The rest of the notebook should be probably fine.

**Comment by ericagol** [comment]
@giordano I think I have fixed this now - if you find the time, could you give it a try?
