### ISSUE TITLE
Setting parameter bounds on a mean model

### ISSUE THREAD

**Issue by bmorris3** [dfm/celerite#130]
Hey @dfm – is it possible to set parameter bounds for custom class inheriting from `Model`? I'm trying to get a celerite fit to a transit light curve like this: 

```python
# Define the model
class MeanModel(Model):
    parameter_names = ['amp', 'depth', 't0', 'c0', 'c1']

    def get_value(self, t):
        original_params.rp = self.depth**0.5
        original_params.t0 = self.t0
        times = t - t.mean()
        return (self.amp * transit_model(t, original_params) + 
                self.c0 * times +  self.c1 * times**2)
```

and I'd like to bound the transit depth between `0 < depth < 1`. I can't figure out how to specify parameter bounds on custom model parameters. 

Thanks in advance!

**Comment by bmorris3** [comment]
I read the source code and found my answer, but it'd be great if it were mentioned in the docs that when initializing `Model`, you can feed it a `bounds` dictionary for each parameter.

**Comment by dfm** [comment]
It is documented here: http://celerite.readthedocs.io/en/stable/python/modeling/#celerite.modeling.Model Where would you expect it to be documented instead?
