### ISSUE TITLE
Ability to provide kernels to predict

### ISSUE THREAD

**Issue by ernewton** [dfm/celerite#132]
Like in George.

**Comment by ericagol** [comment]
@ernewton There is the gp.predict function; see here for an example:  http://celerite.readthedocs.io/en/stable/tutorials/first/

This function uses a standard solver (I think), and thus could be slow for large datasets.  The fast (semi-separable) solver can predict the mean, but not the variance (last time I checked).  But, at the moment I can't find this function - you'll have to ask @dfm

**Comment by dfm** [comment]
@ernewton and I were sitting together when she wrote this - hence the telegraphic style :-)

The suggestion is to allow predicting using a *different* kernel than the one used to compute the model. This would let us show the prediction from each different term.

**Comment by dfm** [comment]
This has been implemented in celerite2: https://celerite2.readthedocs.io/en/latest/api/python/#celerite2.GaussianProcess.predict
