### ISSUE TITLE
worth adding a method for conditional random draws?

### ISSUE THREAD

**Issue by parkus** [dfm/celerite#134]
I made a function that will draw random samples from a covariance matrix that is informed by the existing data. It's nice for filling in gaps with realistic simulated data. I'm using it in completeness tests of a flare detection algorithm where in some cases the gaps left from removing flares significantly affects completeness.

Worth adding it as a method and submitting a PR? 

(P.s. Celerite is rad.)

**Comment by dfm** [comment]
Thanks and sorry that this got lost and I never responded!

I believe that this method already existed at that time (it was [added 4 years ago](https://github.com/dfm/celerite/commit/856e4cc0b38ec8c1918cd880c2a5328330b68c45)) and it still does :D
