### ISSUE TITLE
Implementation of celerite in STAN and R

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#135]
It might be worthwhile to look into creating an implementation of celerite in STAN and/or R as these are widely used languages for statistical analysis.

**Comment by dfm** [comment]
Things only get implemented in Stan when the Stan developers decide that they want them, which is unlikely to happen. If they do, the C++ code exists and it wouldn't be too hard to incorporate! Instead, I've been using celerite inside of PyMC3 (which has most of the key features of Stan) via TensorFlow.

As for R, I don't have the first clue about how to do that and I'm not terribly motivated to figure it out, but this is an open source project and an R developer might know how to wrap C++ code in R :-)
