### ISSUE TITLE
does celerite have a logo?

### ISSUE THREAD

**Issue by davidwhogg** [dfm/celerite#137]
It doesn't need one of course!

But also of course, it could be https://openclipart.org/detail/253460/alergeno-apiocelery

**Comment by dfm** [comment]
Ha!! We don't have one and I'm not sure that I love what you're implying with that one ;-)

**Comment by ericagol** [comment]
That image looks like bok choy.  Here's a logo:

![celerite_logo](https://user-images.githubusercontent.com/243664/47969204-d1532180-e028-11e8-8b5e-ab6061e281ba.png)

**Comment by ericagol** [comment]
I like this color scheme better:

![celerite_logo](https://user-images.githubusercontent.com/243664/47969241-6c4bfb80-e029-11e8-9c68-62b931139267.png)

**Comment by ericagol** [comment]
Of course, we should probably just recruit Rodrigo to make a logo:
[starry](https://rodluger.github.io/starry/_images/starry.png)

**Comment by davidwhogg** [comment]
I don't see why the logo can't be bok choy! 🍆🥑🥦🥒🙂

**Comment by rodluger** [comment]
On it!

**Comment by rodluger** [comment]
How's this??
![image](https://user-images.githubusercontent.com/9323819/48068949-26667300-e1a2-11e8-9c4d-c5301983d5f7.png)

**Comment by ericagol** [comment]
That lightbulb celery (or at least I think that's what it is) looks like it could move at the speed of light!

**Comment by davidwhogg** [comment]
that logo makes absolutely no sense! But I like it!
