### ISSUE TITLE
2 errors running the unit test

### ISSUE THREAD

**Issue by Usuaia** [dfm/celerite#138]
I leave you here enclosed what I get from my try.

Regards.
-------------------------------------------------------------------------------------

platform win32 -- Python 3.7.0, pytest-3.8.2, py-1.6.0, pluggy-0.7.1 -- C:\ProgramData\Anaconda3\python.exe
cachedir: .pytest_cache
rootdir: D:\PAI\WS_PAI\CELERITE, inifile:
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 0 items / 2 errors

=================================== ERRORS ====================================
___________________ ERROR collecting tests/test_celerite.py ___________________
ImportError while importing test module 'D:\PAI\WS_PAI\CELERITE\tests\test_celerite.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_celerite.py:14: in <module>
    import celerite
E   ModuleNotFoundError: No module named 'celerite'
____________________ ERROR collecting tests/test_terms.py _____________________
ImportError while importing test module 'D:\PAI\WS_PAI\CELERITE\tests\test_terms.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_terms.py:9: in <module>
    from celerite import terms
E   ModuleNotFoundError: No module named 'celerite'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 2 error in 8.42 seconds ===========================

**Comment by dfm** [comment]
If you want to run the tests from within the celerite directory, you need to run

```
python setup.py build_ext --inplace
```

instead of 

```
python setup.py install
```

**Comment by Usuaia** [comment]
Thanks dmf, but running the test after your suggestion produces the same errors.

I have also tried to run the test in the Celerite's Anaconda environment directory, then the run produces one but completely different error.

Any other suggestion?

Regards.
