### ISSUE TITLE
problem installing celerite on fresh OpenSuse (gcc: error(s).....)

### ISSUE THREAD

**Issue by 3fon3fonov** [dfm/celerite#139]
Sorry for the long post....

I have the following problem with celerite/pybind11, more specifically
with gcc on a fresh install of OpenSuse leap 42.3 (VM).

trifon@linux-nuuh:~/trifon> gcc --version
gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I tried

sudo zypper install gcc-c++
and
sudo zypper install gcc7

Installation goes smooth but no effect on the error below.
 
 
> 
> trifon@linux-nuuh:~/trifon> bash check_your_system_linux_OpenSuse.sh
> For which Python version we want to check/install packages?
> 1) Python2
> 2) Python3
> #? 1
> gfortran - yes!
> csh - yes!
> pip - yes!
> numpy - yes!
> scipy - yes!
> matplotlib - yes!
> PyQt5 - yes!
> PyQt5.QtSvg - yes!
> qtconsole - yes!
> jupyter - yes!
> dill - yes!
> emcee - yes!
> corner - yes!
> celerite - not installed! Do you wish to install celerite?
> 1) Yes
> 2) No
> #? 1
> [sudo] password for root:
> /usr/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py:83:
> RequestsDependencyWarning: Old version of cryptography ([1, 3, 1]) may
> cause slowdown.
>   warnings.warn(warning, RequestsDependencyWarning)
> Collecting celerite
>   Using cached
> https://files.pythonhosted.org/packages/52/4a/39a9f610607b0e53c0153f2dcf3f07693cfebca78c53f5250b9be46429eb/celerite-0.3.0.tar.gz
> Requirement already satisfied: numpy in
> /usr/lib64/python2.7/site-packages (from celerite) (1.8.0)
> Requirement already satisfied: pybind11 in
> /usr/lib/python2.7/site-packages (from celerite) (2.2.4)
> Installing collected packages: celerite
>   Running setup.py install for celerite ... error
>     Complete output from command /usr/bin/python -u -c "import
> setuptools,
> tokenize;__file__='/tmp/pip-install-tFXScs/celerite/setup.py';f=getattr(tokenize,
> 'open', open)(__file__);code=f.read().replace('\r\n',
> '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
> /tmp/pip-record-HOMuAY/install-record.txt
> --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-2.7
>     creating build/lib.linux-x86_64-2.7/celerite
>     copying celerite/__init__.py -> build/lib.linux-x86_64-2.7/celerite
>     copying celerite/build.py -> build/lib.linux-x86_64-2.7/celerite
>     copying celerite/celerite.py -> build/lib.linux-x86_64-2.7/celerite
>     copying celerite/modeling.py -> build/lib.linux-x86_64-2.7/celerite
>     copying celerite/plot_setup.py -> build/lib.linux-x86_64-2.7/celerite
>     copying celerite/terms.py -> build/lib.linux-x86_64-2.7/celerite
>     copying celerite/timer.py -> build/lib.linux-x86_64-2.7/celerite
>     running egg_info
>     writing requirements to celerite.egg-info/requires.txt
>     writing celerite.egg-info/PKG-INFO
>     writing top-level names to celerite.egg-info/top_level.txt
>     writing dependency_links to celerite.egg-info/dependency_links.txt
>     reading manifest file 'celerite.egg-info/SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     writing manifest file 'celerite.egg-info/SOURCES.txt'
>     copying celerite/solver.cpp -> build/lib.linux-x86_64-2.7/celerite
>     running build_ext
>     testing C++14/C++11 support
>     creating tmp
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpbZr7Sr.cpp -o tmp/tmpbZr7Sr.o -std=c++14
>     gcc: error: unrecognized command line option ‘-std=c++14’
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpGl7U5n.cpp -o tmp/tmpGl7U5n.o -std=c++11
>     gcc -pthread /tmp/tmpeQRWZi.cpp -L/usr/lib64 -lm -o
> /tmp/tmpeQRWZi.cpp.so
>     gcc -pthread /tmp/tmpfdXGwA.cpp -L/usr/lib64 -lstdc++ -o
> /tmp/tmpfdXGwA.cpp.so
>     gcc -pthread /tmp/tmpEf7vug.cpp -L/usr/lib64 -lc++ -o
> /tmp/tmpEf7vug.cpp.so
> 
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:
> cannot find -lc++
>     collect2: error: ld returned 1 exit status
>     testing compiler flags
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpdXC7dc.cpp -o tmp/tmpdXC7dc.o -stdlib=libc++
>     gcc: error: unrecognized command line option ‘-stdlib=libc++’
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmprKQqkJ.cpp -o tmp/tmprKQqkJ.o -fvisibility=hidden
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpMsE852.cpp -o tmp/tmpMsE852.o -Wno-unused-function
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpdN3q81.cpp -o tmp/tmpdN3q81.o -Wno-uninitialized
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpx5sKWs.cpp -o tmp/tmpx5sKWs.o -Wno-unused-local-typedefs
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpJlhM7n.cpp -o tmp/tmpJlhM7n.o -funroll-loops
>     building 'celerite.solver' extension
>     creating build/temp.linux-x86_64-2.7
>     creating build/temp.linux-x86_64-2.7/celerite
>     gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -Icpp/include -Icpp/lib/eigen_3.3.3
> -I/usr/lib64/python2.7/site-packages/numpy/core/include
> -I/usr/include/python2.7 -I/root/.local/include/python2.7
> -I/usr/include/python2.7 -c celerite/solver.cpp -o
> build/temp.linux-x86_64-2.7/celerite/solver.o -DNODEBUG
> -DVERSION_INFO="0.3.0" -std=c++11 -fvisibility=hidden
> -Wno-unused-function -Wno-uninitialized -Wno-unused-local-typedefs
> -funroll-loops
>     In file included from /usr/include/python2.7/pybind11/pytypes.h:12:0,
>                      from /usr/include/python2.7/pybind11/cast.h:13,
>                      from /usr/include/python2.7/pybind11/attr.h:13,
>                      from /usr/include/python2.7/pybind11/pybind11.h:43,
>                      from celerite/solver.cpp:1:
>     /usr/include/python2.7/pybind11/detail/common.h:112:20: fatal error:
> Python.h: No such file or directory
>      #include <Python.h>
>                         ^
>     compilation terminated.
>     error: command 'gcc' failed with exit status 1
> 
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools,
> tokenize;__file__='/tmp/pip-install-tFXScs/celerite/setup.py';f=getattr(tokenize,
> 'open', open)(__file__);code=f.read().replace('\r\n',
> '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
> /tmp/pip-record-HOMuAY/install-record.txt
> --single-version-externally-managed --compile" failed with error code 1
> in /tmp/pip-install-tFXScs/celerite/

All the best,
Trifon

**Comment by dfm** [comment]
It looks like you don't have the Python headers installed. This probably
means that you need to install some sort of python-dev package, but I don't
have any experience with OpenSuse so I'm not sure what to recommend
specifically. Alternatively, you could try out conda (https://conda.io)
because we have a pre-built binary on conda-forge that might work for you.

Hope this helps!

On Tue, Nov 20, 2018 at 9:03 AM 3fon3fonov <notifications@github.com> wrote:

> Sorry for the long post....
>
> I have the following problem with celerite/pybind11, more specifically
> with gcc on a fresh install of OpenSuse leap 42.3 (VM).
>
> trifon@linux-nuuh:~/trifon> gcc --version
> gcc (SUSE Linux) 4.8.5
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions. There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
>
> I tried
>
> sudo zypper install gcc-c++
> and
> sudo zypper install gcc7
>
> Installation goes smooth but no effect on the error below.
>
> trifon@linux-nuuh:~/trifon> bash check_your_system_linux_OpenSuse.sh
> For which Python version we want to check/install packages?
>
>    1. Python2
>    2. Python3
>    #? 1
>    gfortran - yes!
>    csh - yes!
>    pip - yes!
>    numpy - yes!
>    scipy - yes!
>    matplotlib - yes!
>    PyQt5 - yes!
>    PyQt5.QtSvg - yes!
>    qtconsole - yes!
>    jupyter - yes!
>    dill - yes!
>    emcee - yes!
>    corner - yes!
>    celerite - not installed! Do you wish to install celerite?
>    3. Yes
>    4. No
>    #? 1
>    [sudo] password for root:
>    /usr/lib/python2.7/site-packages/pip/_vendor/requests/*init*.py:83:
>    RequestsDependencyWarning: Old version of cryptography ([1, 3, 1]) may
>    cause slowdown.
>    warnings.warn(warning, RequestsDependencyWarning)
>    Collecting celerite
>    Using cached
>
>    https://files.pythonhosted.org/packages/52/4a/39a9f610607b0e53c0153f2dcf3f07693cfebca78c53f5250b9be46429eb/celerite-0.3.0.tar.gz
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__files.pythonhosted.org_packages_52_4a_39a9f610607b0e53c0153f2dcf3f07693cfebca78c53f5250b9be46429eb_celerite-2D0.3.0.tar.gz&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=LPJ0DZ26YXn6NVeOxhYQXWXJbBX_rVUT8T0gxMrXA2U&s=mEKH_rhciW0hQpkUwZ3vrMuHbWTNgeBDVjXleMp7BuU&e=>
>    Requirement already satisfied: numpy in
>    /usr/lib64/python2.7/site-packages (from celerite) (1.8.0)
>    Requirement already satisfied: pybind11 in
>    /usr/lib/python2.7/site-packages (from celerite) (2.2.4)
>    Installing collected packages: celerite
>    Running setup.py install for celerite ... error
>    Complete output from command /usr/bin/python -u -c "import
>    setuptools,
>    tokenize;*file*
>    ='/tmp/pip-install-tFXScs/celerite/setup.py';f=getattr(tokenize,
>    'open', open)(*file*);code=f.read().replace('\r\n',
>    '\n');f.close();exec(compile(code, *file*, 'exec'))" install --record
>    /tmp/pip-record-HOMuAY/install-record.txt
>    --single-version-externally-managed --compile:
>    running install
>    running build
>    running build_py
>    creating build
>    creating build/lib.linux-x86_64-2.7
>    creating build/lib.linux-x86_64-2.7/celerite
>    copying celerite/*init*.py -> build/lib.linux-x86_64-2.7/celerite
>    copying celerite/build.py -> build/lib.linux-x86_64-2.7/celerite
>    copying celerite/celerite.py -> build/lib.linux-x86_64-2.7/celerite
>    copying celerite/modeling.py -> build/lib.linux-x86_64-2.7/celerite
>    copying celerite/plot_setup.py -> build/lib.linux-x86_64-2.7/celerite
>    copying celerite/terms.py -> build/lib.linux-x86_64-2.7/celerite
>    copying celerite/timer.py -> build/lib.linux-x86_64-2.7/celerite
>    running egg_info
>    writing requirements to celerite.egg-info/requires.txt
>    writing celerite.egg-info/PKG-INFO
>    writing top-level names to celerite.egg-info/top_level.txt
>    writing dependency_links to celerite.egg-info/dependency_links.txt
>    reading manifest file 'celerite.egg-info/SOURCES.txt'
>    reading manifest template 'MANIFEST.in'
>    writing manifest file 'celerite.egg-info/SOURCES.txt'
>    copying celerite/solver.cpp -> build/lib.linux-x86_64-2.7/celerite
>    running build_ext
>    testing C++14/C++11 support
>    creating tmp
>    gcc -pthread -fno-strict-aliasing -fmessage-length=0
>    -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
>    -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
>    -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
>    -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
>    -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
>    /tmp/tmpbZr7Sr.cpp -o tmp/tmpbZr7Sr.o -std=c++14
>    gcc: error: unrecognized command line option ‘-std=c++14’
>    gcc -pthread -fno-strict-aliasing -fmessage-length=0
>    -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
>    -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
>    -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
>    -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
>    -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
>    /tmp/tmpGl7U5n.cpp -o tmp/tmpGl7U5n.o -std=c++11
>    gcc -pthread /tmp/tmpeQRWZi.cpp -L/usr/lib64 -lm -o
>    /tmp/tmpeQRWZi.cpp.so
>    gcc -pthread /tmp/tmpfdXGwA.cpp -L/usr/lib64 -lstdc++ -o
>    /tmp/tmpfdXGwA.cpp.so
>    gcc -pthread /tmp/tmpEf7vug.cpp -L/usr/lib64 -lc++ -o
>    /tmp/tmpEf7vug.cpp.so
>
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:
> cannot find -lc++
> collect2: error: ld returned 1 exit status
> testing compiler flags
> gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpdXC7dc.cpp -o tmp/tmpdXC7dc.o -stdlib=libc++
> gcc: error: unrecognized command line option ‘-stdlib=libc++’
> gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmprKQqkJ.cpp -o tmp/tmprKQqkJ.o -fvisibility=hidden
> gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpMsE852.cpp -o tmp/tmpMsE852.o -Wno-unused-function
> gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpdN3q81.cpp -o tmp/tmpdN3q81.o -Wno-uninitialized
> gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpx5sKWs.cpp -o tmp/tmpx5sKWs.o -Wno-unused-local-typedefs
> gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c
> /tmp/tmpJlhM7n.cpp -o tmp/tmpJlhM7n.o -funroll-loops
> building 'celerite.solver' extension
> creating build/temp.linux-x86_64-2.7
> creating build/temp.linux-x86_64-2.7/celerite
> gcc -pthread -fno-strict-aliasing -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
> -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g
> -DOPENSSL_LOAD_CONF -fwrapv -fPIC -Icpp/include -Icpp/lib/eigen_3.3.3
> -I/usr/lib64/python2.7/site-packages/numpy/core/include
> -I/usr/include/python2.7 -I/root/.local/include/python2.7
> -I/usr/include/python2.7 -c celerite/solver.cpp -o
> build/temp.linux-x86_64-2.7/celerite/solver.o -DNODEBUG
> -DVERSION_INFO="0.3.0" -std=c++11 -fvisibility=hidden
> -Wno-unused-function -Wno-uninitialized -Wno-unused-local-typedefs
> -funroll-loops
> In file included from /usr/include/python2.7/pybind11/pytypes.h:12:0,
> from /usr/include/python2.7/pybind11/cast.h:13,
> from /usr/include/python2.7/pybind11/attr.h:13,
> from /usr/include/python2.7/pybind11/pybind11.h:43,
> from celerite/solver.cpp:1:
> /usr/include/python2.7/pybind11/detail/common.h:112:20: fatal error:
> Python.h: No such file or directory
> #include <Python.h>
> ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1
>
> ----------------------------------------
>
> Command "/usr/bin/python -u -c "import setuptools,
> tokenize;*file*
> ='/tmp/pip-install-tFXScs/celerite/setup.py';f=getattr(tokenize,
> 'open', open)(*file*);code=f.read().replace('\r\n',
> '\n');f.close();exec(compile(code, *file*, 'exec'))" install --record
> /tmp/pip-record-HOMuAY/install-record.txt
> --single-version-externally-managed --compile" failed with error code 1
> in /tmp/pip-install-tFXScs/celerite/
>
> All the best,
> Trifon
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dfm_celerite_issues_139&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=LPJ0DZ26YXn6NVeOxhYQXWXJbBX_rVUT8T0gxMrXA2U&s=kF21Jpiq6dw84_DTjuoYsnPPE8GBkd7rK6SYTsF6UPU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAVYSuZBlu9KH1qpkrrZtvut3GVFUAavks5uxAupgaJpZM4YrKkL&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=LPJ0DZ26YXn6NVeOxhYQXWXJbBX_rVUT8T0gxMrXA2U&s=O2MSc5-PBEdjLW-j9qwH4jugg6rGr1BCkyhcHnLnKrY&e=>
> .
>
-- 
Dan Foreman-Mackey
Associate Research Scientist
Flatiron Institute
http://dfm.io

**Comment by 3fon3fonov** [comment]
Dear Dan,

Useful as always!

sudo zypper install python-devel 

fixed the headers problem. (and I thought it is compiler related!)

Now I have similar problems with the numpy headers, but that's another (Suse related)
problem. 

Celerite is installed so this tread is closed!

Thanks again!
Trifon

**Comment by 3fon3fonov** [comment]
I just want to report that the headers were in fact only 1/2 of the problem!
As I suspected the C++11 comparable compiler was also missing in a fresh OpenSuse.
One needs to do:

```
sudo zypper install gcc-c++
sudo zypper install python-devel
```
