### ISSUE TITLE
Derivative of GP

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#14]
[Rajpaul et al.](http://adsabs.harvard.edu/abs/2015MNRAS.452.2269R) claim that various transformations applied to GPs are GPs;  this is important, for example, in detrending RV data due to stellar activity by modeling the RV and activity signals (e.g. log(R'_HK) & BIS).   We should add this capability to Generalized RP code if possible.  They used this formalism to show that Alpha Cen b was not a planet, but instead is [due to a combination of stellar variability & the window function.](http://adsabs.harvard.edu/abs/2016MNRAS.456L...6R).  They complain about the lack of scalability of GPs, so this may be a place we can make an impact if we can figure out how to incorporate the kernel time derivatives into our formalism.  This may introduce sub-matrices into the formalism, but I'm unsure how the multiple kernel components & time-series components will couple;  it also introduces sinusoids (but I think it's the sinusoid of the absolute value of the time differences, so the kernel is still symmetric).  Another issue is that the exponential kernel is not differentiable at zero offset;  however, the approximate Matern kernel is singly differentiable, so this may solve this problem.

**Comment by dfm** [comment]
The derivative of a celerite model is still a celerite model since it's all just a sum of exponentials. Unfortunately it won't be trivial to apply the model to Rajpaul's problem because it is multidimensional. There might be something that we could do to generalize to simple problems like this since they still have parallel time series like your spectral time series ideas but let's punt on that for now and close this.

**Comment by pscicluna** [comment]
Is there a plan to revisit the issue of derivatives in future? This would be useful even for one-D problems, for example to condition using the derivatives or make the functions more monotonic (with virtual points). In particular, I have a problem where I am observing one thing, but am actually interested in predicting its derivative. What would be required to implement this with celerite?

**Comment by ericagol** [comment]
@tagordon is interested in looking into this.

**Comment by dfm** [comment]
This has been implemented in celerite2: https://celerite2.readthedocs.io/en/latest/api/python/#celerite2.terms.TermDiff
