### ISSUE TITLE
Getting nans out of gp.predict

### ISSUE THREAD

**Issue by nespinoza** [dfm/celerite#141]
Hi @dfm! 

 I encountered a case on which `celerite` is returning `nan` values when doing gp.predict() and was wondering if you could track down what is going on. I'm using your `celerite` rotational kernel given by:

 ```
import numpy as np
 import celerite
 from celerite import terms

 class RotationTerm(terms.Term):
    parameter_names = ("log_amp", "log_timescale", "log_period", "log_factor")
    def get_real_coefficients(self, params):
        log_amp, log_timescale, log_period, log_factor = params
        f = np.exp(log_factor)
        return (
            np.exp(log_amp) * (1.0 + f) / (2.0 + f),  
            np.exp(-log_timescale),
        )    

    def get_complex_coefficients(self, params):
        log_amp, log_timescale, log_period, log_factor = params
        f = np.exp(log_factor)
        return (
            np.exp(log_amp) / (2.0 + f),  
            0.0, 
            np.exp(-log_timescale),
            2*np.pi*np.exp(-log_period),
        )
```
Using the kernel, the following code snippet gives you back a double and a set of `nan`'s:

```
times = np.array([2455081.7836,2455756.7933,2456583.6719,2457613.6768])
residuals = np.array([-1.91,-7.12,-2.48,1.29])
B,L,Prot,C = 4.07,0.219,14.69,0.006

kernel = terms.TermSum(RotationTerm(log_amp=np.log(B),\
                                                    log_timescale=np.log(L),\
                                                    log_period=np.log(Prot),\
                                                    log_factor=np.log(C)))

gp = celerite.GP(kernel, mean=0.0)
gp.compute(times)
gpmodel_real,gpmodel_var = gp.predict(residuals, times, return_var=True)
print gp.sample_conditional(residuals,times)
```
In particular, in my computer I get `[-1.91457672         nan         nan         nan]`. I think I might be stepping in a weird part of the parameter space for the coefficients that this imply, but I'm not really sure. The real coefficients here would be `(2.04,4.56)` and the complex would be `(2.029,0,4.57,0.43)`. I see nothing wrong directly here. Also, the implied covariance matrix in this case is a diagonal matrix, which should be an easy one to handle...so I'm a bit lost as to what is going on. 

Thanks in advance for any pointers!

N.

**Comment by dfm** [comment]
@nespinoza: Thanks for the report. This happens when the length scale is short (0.2 days) and your data points are so far apart (~1000 days)! This means that the data are perfectly de-noised and the predictive covariance is zero. You can do the following to make it not produce nans:

```python
gpmodel_mu, gpmodel_cov = gp.predict(residuals, times, return_cov=True)

# This is the new part...
gpmodel_cov[np.diag_indices_from(gpmodel_cov)] += 1e-8  # some small number

sample = np.random.multivariate_normal(gpmodel_mu, gpmodel_cov)
```

and I can add an option to `sample_conditional`, but the samples will always be "made up" for a data set like this!
