### ISSUE TITLE
GP Prediction Extremely Slow With >10k Points

### ISSUE THREAD

**Issue by spencerw** [dfm/celerite#144]
We've been using gp.predict to model stellar lightcurves and have found that it gets INCREDIBLY slow when using more than roughly 10k data points. Here is a link to a minimal reproduction of the problem:

[https://github.com/spencerw/celerite_timing_issue](https://github.com/spencerw/celerite_timing_issue)

Not sure if this is related, but I've been using Celerite on our local supercomputer to process lightcurves in parallel and found that processes will ocassionally die when running gp.predict on more than about 10k data points. I'm having a tough time reliably reproducing this problem, unfortunately, but maybe the timing issue I mentioned above is related.

**Comment by dfm** [comment]
There were several issues in this notebook (calling `compute` twice, including the optimization in the timing, etc.). But yes, the bottleneck for large problems is compute including the variance! This will scale poorly – O(M^2 + N*M) where N is the size of your training set and M is the number points where you're predicting – until @ericagol figures out something faster. The crashes might be related to the fact that allocating a 10,000 x 10,000 numpy array is not super fun :). If you really need the predicted variance then there's nothing that we can do to help you, sorry! If you don't really need the variance, then you'll get blazing fast performance and lower memory usage with:

```python
mu = gp.predict(y, return_cov=False, return_var=False)
```

if you want to predict at the same `x` as your training points (what it seems like you want here!) or

```python
mu = gp.predict(y, t, return_cov=False, return_var=False)
```

for some `t != x`.

**Comment by spencerw** [comment]
I thought Celerite did something more space efficient than simply allocating a 10k x 10k array? If not, that would definitely explain the crashes.

In any case, thank you for taking a look! The extra call to compute came from the fact that I pulled this from a script which looks for flares in TESS lightcurves by iteratively fitting a GP and throwing out outliers. Doing this with a lightcurve with 20k points gets realllly slow :( which is why I was so concerned about this.

Our workaround for this has been to train the GP using a downsampled version of the lightcurve. Which works okay as long as there is no super short timescale variability.

**Comment by dfm** [comment]
I'd recommend using one of the methods that I suggest above instead of down sampling. You don't generally need the predicted variance for large datasets like that; just use the sample variance of the residuals to do the rejection! And then it'll be super fast and memory efficient. The predicted mean is fast, but the variance does require allocating a huge matrix.

**Comment by ericagol** [comment]
Celerite does something space efficient for the Cholesky decomposition and other operations such as matrix multiplication, solution of linear equations, computing the likelihood, and predicting the mean.  The only operation for which we couldn't find an efficient implementation of is the prediction of the variance of the mean, which happens to be the precise operation you were asking it to do.

So, you have a few options (which depends on the precise application you have in mind):

1).  You could predict the mean and variance at a smaller number of points.  For instance, if you are masking some data and would like to predict the mean and variance at the masked data points, then M is small, and the scaling should be fast.  Or  if you could live with a prediction for, say, every tenth data point, this would make the sampling more efficient as well.

2).  There might be a Monte Carlo means of computing the mean prediction which would be faster.  I'd have to think about this some more.

3).  Or, as Dan suggests, you can run it without the variance prediction.

**Comment by gully** [comment]
Thanks Dan and Eric for the thoughtful responses here!  I had hit similar fundamental limitations at one point and was happy to see my solution among the ones described.  I've been working on demos of the GPyTorch framework, which implements fast predictive variances using the approach described here:
https://arxiv.org/abs/1803.06058

To be clear, what Dan described as detecting outliers from mean-model residuals is likely to work for the problem described here with dense time sampling.  I suspect prediction tasks or sparse sampling may benefit more from the variance.

Thanks again!
