### ISSUE TITLE
TypeError: pybind11_object.__new__(celerite.solver.CholeskySolver) is not safe,

### ISSUE THREAD

**Issue by 3fon3fonov** [dfm/celerite#145]
Hello! 

It seems that for some reason I cannot dump object which contains celerite class in it.
I am using dill, not pickle, so the problem could be in dill. 
The thing is that dill+celerite works perfectly on Python 3. 
I am trying to move away from Python 2, but still some tips on how to avoid this crash would be appreciated. 

  File "/home/trifonov/.local/lib/python2.7/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/trifonov/.local/lib/python2.7/site-packages/dill/_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
  File "/usr/lib64/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: pybind11_object.__new__(celerite.solver.CholeskySolver) is not safe, use object.__new__()

**Comment by dfm** [comment]
This [seems to be a known issue with pybind11](https://discuss.pytorch.org/t/pybind11-object-new-topleveltracedmodule-is-not-safe-use-object-new/32206). I'm not sure that I have the skills to fix it if pytorch hasn't :)
