### ISSUE TITLE
Typo in equation (60) in paper

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#146]
@eford pointed out that equation (60) in the paper should have an upper limit of `J`, not `2J`.  Not sure if an erratum is warranted...

**Comment by dfm** [comment]
I definitely don't think that something that small requires an erratum. Anyone implementing that equation will quickly realize what's going on! We should fix the version of the paper in the repo though.

**Comment by dfm** [comment]
It's already a `J` on arXiv, I'm not sure when that `2J` got introduced.
