### ISSUE TITLE
Implementing an instrumental systematics kernel with celerite

### ISSUE THREAD

**Issue by victoriafoing** [dfm/celerite#147]
Is there a straightforward way to build a kernel to model instrumental systematics in celerite?
The kernel I would like to build is the squared exponential kernel.

**Comment by dfm** [comment]
I haven't found any examples where a squared exponential kernel is a better representation of real data than something like the SHOTerm which is built into celerite. You can approximate a squared exponential using a mixture of terms, but I expect that would be unstable and probably wouldn't gain you anything.

**Comment by victoriafoing** [comment]
Thanks for the quick reply. I'm working with very noisy lightcurves so I would like to model the instrumental systematics. So you're saying I could use a granulation kernel to do this?

**Comment by dfm** [comment]
For sure! Depending on the details of your data there might be better choices, but I can't see any reason why an exponential squared kernel would be it!

I'd be happy to provide more specifc suggestions if you want to drop me an email.
