### ISSUE TITLE
Approximate Squared-Exponential and Matern-5/2 kernels

### ISSUE THREAD

**Issue by temuller** [dfm/celerite#148]
Hi,

this might sound like a naive question, but is there a way to build Squared-Exponential and Matern-5/2 kernels? I am asking this because `george` has these built-in kernels, but  in `celerite` only the approximate Matern-3/2 kernel is implemented. I am mainly interested in the Squared-Exponential kernel as I am looking for a kernel with a similar behavior. Thanks!

**Comment by dfm** [comment]
It would be possible to approximate a squared exponential, but it might require a large number of terms and there's no guaruntee that it would be numerically stable. Can you say more about what behavior you're trying to achieve? I've never found a situation where an exponential squared was "better" than a `SHOTerm` by any definition I can come up with!

**Comment by temuller** [comment]
I want to fit a set of data points that ideally should follow a straight (horizontal) line. Hence, I am looking for a kernel that doesn't "wiggle" too much, i.e., a "smooth" kernel.

**Comment by dfm** [comment]
That's certainly possible with a SHOTerm. Sounds like your `w0` parameter is too large if you're seeing too much high frequency noise!

**Comment by temuller** [comment]
Thanks, I will try to constrain `w0` better then.

**Comment by dfm** [comment]
But: please feel free to post a specific example (with sample code) that demonstrates your issue and I'm happy to help.
