### ISSUE TITLE
Log of negative roots in CARMA solver

### ISSUE THREAD

**Issue by ywx649999311** [dfm/celerite#149]
I am not familiar with C++, but wonder if this line will cause problems as it is taking the log of negative numbers and return possible wrong conversions between CARMA and celerite. 

https://github.com/dfm/celerite/blob/ad3f471f06b18d233f3dab71bb1c20a316173cae/cpp/include/celerite/carma.h#L86

**Comment by dfm** [comment]
These are all complex numbers so I believe it is fine. Try some examples and see if there are issues!

**Comment by ywx649999311** [comment]
Thanks for pointing that out, I certainly missed that. I did a test using a simple CARMA(2,1). I hard coded the C++ CARMA coefficient conversion code in Python and compare it to the values returned by the Celerite CARMA_solver. They disagree, am I doing anything wrong here? I am trying to follow the C++ code as much as I can, but I could certainly have missed something.

```python
from scipy.special import logsumexp

# define CARMA parameters following carma_pack notation
sigma = 1
arpar = np.array([0.8, 2]) # low to high order
mapar = np.array([0.5])

arroots = np.roots(np.append([1], arpar[::-1]))
r1 = np.complex(arroots[0])
r2 = np.complex(arroots[1])

# let's only looking at the 1st Celerite term or j=1 case
term1 = np.log(sigma)
term2 = np.log(sigma)

term1 = logsumexp([term1, np.log(mapack[0])+np.log(r1)])
term2 = logsumexp([term2, np.log(mapack[0])+np.log(-r1)])

full_term = 2*np.log(sigma) + term1 + term2 - np.log(np.complex(-r1.real))
full_term -= (np.log(r2-r1) + np.log(np.conj(r2) + r1))
full_term = np.exp(full_term)
a_1 = 0.5*full_term.real
c_1 = -r1.real

# now the second Celerite term
term1 = np.log(sigma)
term2 = np.log(sigma)

term1 = logsumexp([term1, np.log(mapack[0])+np.log(r2)])
term2 = logsumexp([term2, np.log(mapack[0])+np.log(-r2)])

full_term = 2*np.log(sigma) + term1 + term2 - np.log(np.complex(-r2.real))
full_term -= (np.log(r1-r2) + np.log(np.conj(r1) + r2))
full_term = np.exp(full_term)
a_2 = 0.5*full_term.real
c_2 = -r2.real

print('Hand Code CARMA Solver for CARMA(2,1)')
print(f'a_1: {a_1}')
print(f'c_1: {c_1}')
print(f'a_2: {a_2}')
print(f'c_2: {c_2}')

print('\nSolution provided by Celerite CARMA Solver')
carma_solver = CARMASolver(np.log(sigma), np.log(arpar), np.log(mapar))
carma_solver.get_celerite_coeffs()  
```

Hand Code CARMA Solver for CARMA(2,1)
a_1: -0.09200849718747373
c_1: 1.4472135954999579
a_2: 0.4670084971874737
c_2: 0.5527864045000421

Solution provided by Celerite CARMA Solver
(array([-0.11239837,  1.42489837]),
 array([0.5527864, 1.4472136]),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64))

**Comment by dfm** [comment]
I'm not too sure what to say here! As I explained to you over email, I don't think that using the CARMA parameterization is necessary and I don't have the capacity to support this feature so you're on your own with this one!
