### ISSUE TITLE
Prediction/interpolation

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#15]
See if there is an O(N) method for computing variance of predicted/interpolated times.

**Comment by dfm** [comment]
I can get predictive means and variances in `O(N*M)`. If we want to predict at the locations of the observations, we can get means in `O(N)` but I haven't worked out how to get the predicted variances in better than `O(N^2)`. I feel like there must be a general `O(N+M)` method, but I haven't worked it out yet.

**Comment by ericagol** [comment]
@dfm @sivaramambikasaran I think I've figured out how to do prediction (at future times) in O(J^2N + J(N+M)) for the mean an O(J^2(M+N)) for the variance.  However, this doesn't work for interpolation (i.e. all of the predicted times need to be after the last of the measured times to avoid sign changes in the absolute values).  I've written part of this up (below), but haven't implemented it yet.  The current version works for complex arithmetic;  it probably could be made real with a bit more effort.

[Semi_separable_celerite_decomposition.pdf](https://github.com/dfm/celerite/files/965694/Semi_separable_celerite_decomposition.pdf)

**Comment by dfm** [comment]
I had worked that out that method for the mean too. I think that there's probably something that we can do using two passes (one forward and one backward) with similar arithmetic.

**Comment by dfm** [comment]
PS. Nice work on the variance!

**Comment by ericagol** [comment]
I had written up a method for interpolating the mean in O(M) operations, but it was commented out & then deleted, but can probably be found in the Github repo.  I didn't have success with the variance.

**Comment by dfm** [comment]
I coded up a sketch of your idea (+interpolation) for the mean. You probably did this before, but here's my version: https://gist.github.com/dfm/3167d20177c95d6e9aeb66894a8fac2c

I think I have an idea for the variance using the Cholesky factor but I haven't fully worked it through.

**Comment by ericagol** [comment]
I think the backward & forward pass approach should work for the variance as well!

**Comment by ericagol** [comment]
That's a clever approach to solving this!  It may be worth adding time differences to avoid overflow/underflow.

**Comment by ericagol** [comment]
I think the variance can be computed in the same forward/backward manner as the mean.

**Comment by dfm** [comment]
Good call on using time differences. It's easy to construct realistic models where we end up with numerical issues in the way I implemented it.

I agree that a similar procedure should work for the variance, but I have an intuition that we'll need to use `L^{-1} k` instead of `K^{-1} k`.

**Comment by ericagol** [comment]
Oh yeah, I think I can see what you mean.

**Comment by dfm** [comment]
Still no luck on the variance, but I did update the algorithm to be pre-conditioned and only use real arithmetic.

The updated gist is here: https://gist.github.com/dfm/3167d20177c95d6e9aeb66894a8fac2c
