### ISSUE TITLE
Questions about SHO Equations in paper

### ISSUE THREAD

**Issue by victoriafoing** [dfm/celerite#150]
Hi there,

I have some questions about the SHO equations in the paper.

![image](https://user-images.githubusercontent.com/28833172/87955833-8a33eb00-caae-11ea-9666-d8afd6c70c45.png)

1) How do you derive the PSD equation 20? I looked in the Anderson et al. 1990 paper and could not find it.
2) What does the parameter S<sub>0</sub> represent? How can I interpret the values of S<sub>0</sub>?

**Comment by ericagol** [comment]
Hi @victoriafoing,

Thanks for the questions!

Equation (20) can be derived by computing the absolute value squared of equation (4):

![image](https://user-images.githubusercontent.com/243664/87960797-ac574a00-ca69-11ea-97ab-a57f60d326dd.jpeg)

Then the power spectrum (their equation 6) is given as:

![image](https://user-images.githubusercontent.com/243664/87961108-1b34a300-ca6a-11ea-9abf-946c587dc094.jpeg)

With the substitutions: 

![image](https://user-images.githubusercontent.com/243664/87961154-2d164600-ca6a-11ea-979e-3e52c9469bc6.jpeg)

and 

![image](https://user-images.githubusercontent.com/243664/87961192-3e5f5280-ca6a-11ea-8b51-73016eab86bd.jpeg)

this yields an expression which is proportional to our equation (20).

Then, S<sub>0</sub> is the normalization constant of the power spectrum, which is the Fourier transform of the kernel.

I find it easiest to interpret S<sub>0</sub> in terms of the kernel definition in our equation (23).  When 
![image](https://user-images.githubusercontent.com/243664/87961659-e412c180-ca6a-11ea-9544-5699b6aaeb45.jpeg), then 
![image](https://user-images.githubusercontent.com/243664/87961719-fb51af00-ca6a-11ea-992d-e15007082196.jpeg), which is the limiting amplitude of the kernel at zero time lag (which is in addition to a white-noise amplitude which is only present at zero time lag).  The kernel has units of the y<sup>2</sup> (let's say this is [y]<sup>2</sup>), and 
![image](https://user-images.githubusercontent.com/243664/87962161-9e0a2d80-ca6b-11ea-9317-9d154977f879.jpeg) has units of 2\pi/[t] (using whatever "time" unit you are using, [t], or other independent vector for a general GP),
 which is in units of the quantity you have a vector of measurements of, and so S<sub>0</sub> should equal 
![image](https://user-images.githubusercontent.com/243664/87962430-078a3c00-ca6c-11ea-9213-7e5b3d9066c8.jpeg) and  have units of [y]<sup>2</sup>[t].  The quantities Q and 
![image](https://user-images.githubusercontent.com/243664/87962544-36a0ad80-ca6c-11ea-8726-c6621b1e440d.jpeg) can be fit to your dataset.

**Comment by dfm** [comment]
"i" is the imaginary unit and when you take the absolute value squared of the numerator, it is equal to the denominator, so it cancels.
