### ISSUE TITLE
possible mistake in the example of the kernel building

### ISSUE THREAD

**Issue by pilchat** [dfm/celerite#152]
Hi,

I am following the example here:

https://celerite.readthedocs.io/en/stable/python/kernel/

In "get_real_coefficients", shouldn't the first coefficient multiplied by 2? Such as "2 * np.exp(log_a) * (1.0 + b) / (2.0 + b)".

Thanks

**Comment by dfm** [comment]
It looks right to me! Are you getting confused by the complex notation above? There are various factors of 2 that appear when you switch to sin and cos. Or am I missing something else?

**Comment by pilchat** [comment]
I have just expanded cos(z)=(cos(iz)+cos(-iz))/2 and then followed the math
to reorder the expression as a sum of real/complex exponentials.

Can you please recheck the factor "1/2" in the definition of the kernel
(first row)? Can it be that you multiplied it with the real exponential?

**Comment by dfm** [comment]
I'm not sure which row you're referring to here!

The definition of the coefficients are:

- for real terms: `a * exp(-c * tau)` -> `get_real_coefficients()` returns `a` and `c` (both real)
- for complex terms: `a * exp(-c * tau) * cos(d * tau) + b * exp(-c * tau) * sin(d * tau)` -> `get_complex_coefficients()` returns `a`, `b`, `c`, and `d` (all real)

Hope this helps!

**Comment by pilchat** [comment]
let me explain better. If I expand the kernel

`k(\tau) = \frac{a}{2+b}\,e^{-c\,\tau}\left[
    \cos\left(\frac{2\,\pi\,\tau}{P}\right) + (1+b)
\right]`

such as to put it in the general form 
`k(\tau) = \sum_{j=1}^J \frac{1}{2}\left[
    (a_j + i\,b_j)\,e^{-(c_j+i\,d_j)\,\tau} +
    (a_j - i\,b_j)\,e^{-(c_j-i\,d_j)\,\tau}
\right]`

than I obtain

`k(\tau)=\frac{1}{2}\left[2\,a\,\frac{1+b}{2+b}\,e^{-c\,\tau}+\frac{a}{2+b}e^{-(c+i\,\frac{2\pi}{P})\tau}+\frac{a}{2+b}e^{-(c-i\,\frac{2\pi}{P})\tau}\right]`

Then, I suspect that the definition of "get_real_coefficients" should be:

>def get_real_coefficients(self, params):

>        log_a, log_b, log_c, log_P = params

>        b = np.exp(log_b)

>        return (

>            2 * np.exp(log_a) * (1.0 + b) / (2.0 + b), np.exp(log_c),

>        )

where I multiplied by 2 the first element that is returned. Is it correct, or am I missing something?

Thanks

**Comment by dfm** [comment]
Look again at the definition that I gave above:

```
k(\tau) = \frac{a}{2+b}\,e^{-c\,\tau}\left[ \cos\left(\frac{2\,\pi\,\tau}{P}\right) + (1+b) \right]
```

This can equivalently be written:

```
k(\tau) = \frac{a}{2+b}\,e^{-c\,\tau}\,\cos\left(\frac{2\,\pi\,\tau}{P}\right) + \frac{a}{2+b}\,e^{-c\,\tau}\,(1+b)
```

Therefore, the real term is:

```
k_real(\tau) =\frac{a}{2+b}\,e^{-c\,\tau}\,(1+b)
```

and the complex term is:

```
k(\tau) = \frac{a}{2+b}\,e^{-c\,\tau}\,\cos\left(\frac{2\,\pi\,\tau}{P}\right)
```

So the sample code is correct!

**Comment by pilchat** [comment]
I found my mistake. for the real part of the kernel, the two exponentials in the definitions are the same and the (1/2) factor cancels out.

that fixes everything.

thanks again

**Comment by dfm** [comment]
Awesome! No worries - glad we got it sorted out!
