### ISSUE TITLE
Obvious noise fitting

### ISSUE THREAD

**Issue by HkmMerwan** [dfm/celerite#154]
Hello, first thank you for your work but I find myself with an obvious noise fitting and can not manage to figure out why. 

I want to use a Matern32 kernel on my data points 
`sigma = 0.42`
`rho = 22.4`
`kernel = terms.Matern32Term(log_sigma = np.log(sigma), log_rho = -np.log(rho))`
`gp = celerite.GP(kernel, mean=np.mean(confirmed))`
`gp.compute(time)`

I fit the hyperparameters using a MLE and get this fit 

![image](https://user-images.githubusercontent.com/76592606/103138162-14bcee00-46d0-11eb-8003-4ef2c85440f5.png)

`OrderedDict([('kernel:log_sigma', -0.033745618483103104), ('kernel:log_rho', 0.13076586675369392)])`

I used GPyTorch in order to compare, using a Type-II MLE to train the hyperparameters and got this result 

![image](https://user-images.githubusercontent.com/76592606/103138220-a3316f80-46d0-11eb-8c7a-c499d950525c.png)

`Parameter name: covar_module.raw_outputscale               value = -0.6452005505561829`
`Parameter name: covar_module.base_kernel.raw_lengthscale   value = 22.3851871490478`

What is that I am doing wrong in this case ? Thank you for your help.

P.S : Here are my data points  : [-5.3907e-01, -5.3893e-01, -5.3900e-01, -5.3907e-01, -5.3907e-01,
        -5.3900e-01, -5.3900e-01, -5.3907e-01, -5.3907e-01, -5.3900e-01,
        -5.3907e-01, -5.3907e-01, -5.3907e-01, -5.3907e-01, -5.3907e-01,
        -5.3907e-01, -5.3872e-01, -5.3907e-01, -5.3907e-01, -5.3907e-01,
        -5.3907e-01, -5.3907e-01, -5.3907e-01, -5.3900e-01, -5.3907e-01,
        -5.3907e-01, -5.3907e-01, -5.3907e-01, -5.3907e-01, -5.3907e-01,
        -5.3907e-01, -5.3907e-01, -5.3907e-01, -5.3893e-01, -5.3879e-01,
        -5.3767e-01, -5.3774e-01, -5.3605e-01, -5.3697e-01, -5.3479e-01,
        -5.3760e-01, -5.3373e-01, -5.2937e-01, -5.2572e-01, -5.1574e-01,
        -5.2663e-01, -5.1897e-01, -5.1292e-01, -5.0322e-01, -5.3907e-01,
        -4.4150e-01, -4.8178e-01, -5.3654e-01, -3.8787e-01, -4.6653e-01,
        -4.4003e-01, -4.0931e-01, -4.1339e-01, -4.1922e-01, -3.7775e-01,
        -3.0253e-01, -3.8098e-01, -3.3086e-01, -2.6365e-01, -2.7230e-01,
        -2.1255e-01, -3.5609e-01, -2.3301e-01, -2.7868e-03, -1.9856e-01,
        -3.9103e-01, -1.7185e-01, -1.7393e+00, -4.7897e-01, -3.5251e-01,
        -7.8448e-01, -2.6808e-01, -2.7307e-01, -4.2906e-01, -4.3750e-01,
         3.0282e+00, -3.1827e-01,  6.8745e-01, -3.1357e-01,  3.4511e-01,
        -4.0614e-01, -2.7153e-01, -4.6231e-01, -3.6706e-01, -3.5167e-01,
        -4.1254e-01, -6.5928e-01, -3.4147e-01, -4.2112e-01, -4.9458e-01,
        -2.7996e-01, -3.1891e-01, -6.4135e-01, -4.5345e-01, -5.0210e-01,
        -4.8340e-01, -5.1370e-01, -4.9957e-01, -4.6055e-01, -2.4833e-01,
        -4.8699e-01, -5.0175e-01, -5.0189e-01, -5.2157e-01, -5.1700e-01,
        -4.8614e-01, -5.0245e-01, -4.9394e-01, -5.0301e-01, -5.0990e-01,
        -5.2923e-01, -5.0786e-01, -5.0386e-01, -5.0519e-01, -5.2031e-01,
        -4.8593e-01, -5.0069e-01, -5.6993e-01, -5.1623e-01, -5.2115e-01,
        -5.2698e-01, -3.0408e-01, -4.9732e-01, -4.1289e-01, -5.2284e-01,
        -5.1046e-01, -5.8456e-01, -7.6585e-01, -2.3258e-01, -4.9823e-01,
        -4.9887e-01, -5.1510e-01, -5.1981e-01, -5.0020e-01, -4.9514e-01,
        -5.1349e-01, -4.8270e-01, -5.0414e-01, -5.1166e-01, -5.2951e-01,
        -4.9247e-01, -5.0477e-01, -4.9788e-01, -4.8375e-01, -4.9556e-01,
        -5.1496e-01, -5.2909e-01, -4.9001e-01, -5.2024e-01, -5.2115e-01,
        -4.5029e-01, -5.0758e-01, -5.6761e-01, -4.9373e-01, -5.0807e-01,
        -4.6948e-01, -5.0118e-01, -5.0118e-01, -5.1391e-01, -5.3830e-01,
        -4.6751e-01, -5.0716e-01, -4.8129e-01, -5.0786e-01, -4.8881e-01,
        -5.2143e-01, -5.3795e-01, -4.3904e-01, -5.3472e-01, -4.8797e-01,
        -4.9908e-01, -4.8080e-01, -5.2762e-01, -5.3879e-01, -4.0474e-01,
        -4.9725e-01, -4.7433e-01, -4.5219e-01, -4.6238e-01, -5.3289e-01,
        -5.3907e-01, -3.6418e-01, -4.9943e-01, -4.3574e-01, -4.4143e-01,
        -4.4713e-01, -5.3465e-01, -5.3886e-01, -3.0288e-01, -4.7082e-01,
        -4.1901e-01, -4.2653e-01, -3.7128e-01, -5.3415e-01, -5.3661e-01,
        -2.0650e-01, -4.3968e-01, -3.5645e-01, -3.5082e-01, -3.3360e-01,
        -3.1342e-01, -3.2798e-01, -4.9338e-01, -3.9012e-01, -2.7392e-01,
        -2.0165e-01, -1.8696e-01, -2.9487e-01, -2.1009e-01, -4.0017e-01,
        -2.8488e-01, -5.1890e-01,  2.4845e-01, -1.9433e-03, -1.5526e-01,
        -1.6187e-01, -3.2024e-01, -1.8028e-01, -3.9060e-02, -3.8427e-02,
         8.1920e-02,  6.5049e-02, -4.5878e-02, -2.3919e-01, -6.5420e-02,
         6.6806e-02,  1.4715e-01,  1.2937e-01,  2.5787e-01, -9.3047e-02,
        -8.9462e-02,  1.1061e-02,  1.7731e-01,  1.8069e-01,  3.9115e-01,
         4.1414e-01,  2.0156e-01, -1.4971e-01,  1.6979e-01,  3.9523e-01,
         5.7512e-01,  5.9297e-01,  4.6053e-01,  2.0852e-01, -2.3687e-01,
         2.3644e-02,  4.7080e-01,  3.7836e-01,  3.3513e-01,  6.1996e-01,
         3.3991e-01, -1.4268e-01,  2.5597e-01,  7.9324e-01,  6.8422e-01,
         9.4333e-01,  1.3362e+00,  5.8123e-01,  1.0849e-01,  4.1878e-01,
         1.0779e+00,  1.5527e+00,  1.2628e+00,  1.7177e+00,  1.5583e+00,
         4.6538e-01,  8.9328e-01,  1.3886e+00,  2.3299e+00,  2.4722e+00,
         2.6429e+00, -7.3997e-02,  4.5932e+00,  1.8849e+00,  2.1005e+00,
         2.7376e+00,  2.9387e+00,  1.9262e+00,  2.7071e+00,  6.9187e+00,
         4.5645e+00, -3.7780e+00,  3.5245e+00,  3.7456e+00,  5.5524e+00,
         2.1717e+00,  9.6695e-01,  1.0505e+00,  2.0201e+00,  1.7545e+00,
         1.1526e+00,  1.7074e+00,  1.3724e+00,  1.6740e-01,  2.6666e+00,
         1.4923e+00,  9.1858e-01,  1.0963e+00,  7.0305e-01,  3.8391e-01,
        -1.8324e-01,  1.5833e-01,  6.3866e-01,  3.7484e-01,  3.5889e-01,
         3.3801e-01,  1.4722e-01, -2.3301e-01,  4.8881e-02,  4.6110e-01,
         3.5980e-01,  2.7010e-01,  3.6648e-01,  2.3060e-01, -2.9930e-01,
         4.4767e-01,  4.9252e-01,  4.3607e-01,  4.0915e-01, -5.3907e-01,
         1.2521e+00, -3.1469e-01,  2.8022e-01,  7.0657e-01,  7.5423e-01,
         5.8601e-01,  6.8604e-01,  3.6064e-01, -1.2011e-01,  2.9471e-01,
         5.1804e-01,  9.8761e-01]

**Comment by dfm** [comment]
You must be fitting a white noise component in the GPyTorch model! In celerite, you should include a [JitterTerm](https://celerite.readthedocs.io/en/stable/python/kernel/#celerite.terms.JitterTerm).

Even so, it's not obvious to me that a stationary GP is a good choice for your particular data set.

**Comment by dfm** [comment]
(I should mention that I know this because *without* a white noise term, the model will exactly go through every data point by construction...)

**Comment by HkmMerwan** [comment]
Ok thank you for the quick answer it does give a similar result now ! 

Yes I was trying to compare GPyTorch and celerite on random data with a random kernel. Now I have data for my work on which I am trying to do a Gaussian regression using celerite and might want some help. These data come from different orders of a spectrograph on which I was forgetting to add a jitter and was getting this result : 

![image](https://user-images.githubusercontent.com/76592606/103139005-fce96800-46d7-11eb-83b4-280e4cf22c90.png)
`Final log-likelihood: -34152.13490724329`
`OrderedDict([('kernel:log_sigma', 7.880630186965559), ('kernel:log_rho', -3.6806385290403085), ('mean:alpha', -15196058.545724938), ('mean:beta', 20969.494149527465), ('mean:gamma', -7.232764975132396)])`

And once I add the jitter I still get : 

![image](https://user-images.githubusercontent.com/76592606/103139232-78e4af80-46da-11eb-8fb5-b52bda4b5f74.png)

`Final log-likelihood: -34136.52418631356`
`OrderedDict([('kernel:terms[0]:log_sigma', 7.932584498094634), ('kernel:terms[0]:log_rho', -3.6436370800533444), ('kernel:terms[1]:log_sigma', -2.758714124608422), ('mean:alpha', -15196058.545724858), ('mean:beta', 20969.494266574093), ('mean:gamma', -7.232530879898518)])`

I am fitting a second orderl polynomial model 
```

class MeanModel(Model):
    parameter_names = ("alpha", "beta", "gamma")

    def get_value(self, t):
        return self.alpha + self.beta * t + self.gamma * t * t


    def compute_gradient(self, t):
        dalpha = np.ones(len(t))
        dbeta = t
        dgamma = 2 * t
        return np.array([dalpha, dbeta, dgamma])
```
and a simple Matern32 kernel 

```
    rho = .03
    sigma = np.var(y)
    kernel = terms.Matern32Term(log_sigma = np.log(sigma),log_rho = np.log(rho))
    #kernel += terms.JitterTerm(log_sigma = np.log(sigma))

```
This is the spectrum of a Fabry-Pérot and I wish it could retrieve the sharp lines of the spectrum as in this paper [https://arxiv.org/abs/1912.09563]

Following this paper, it would be normal to have an obvious noise fitting for a Matern32 kernel but would not happen using a Matern52 kernel. So here is my next question, is there an existing robust way to implement a Matern52 kernel ? I was thinking to use 

![image](https://user-images.githubusercontent.com/76592606/103139379-d299a980-46db-11eb-83a0-0eec0c7db2e8.png)

for small ε but I figured I might as well ask how you do it :)

Thank you !

**Comment by dfm** [comment]
I'm happy to chat about this via email after the holidays. Send me an email (should be easy enough to find!) and I'll get back to you in the new year.
