### ISSUE TITLE
Question about gp.predict and gp.log_likelihood

### ISSUE THREAD

**Issue by caseylam** [dfm/celerite#162]
I had a question about some of the results coming out of celerite.

I'm fitting some data at times `t`. For a set of model parameters `theta`, I can calculate the likelihood using `gp.log_likelihood`. However, when I try to use `gp.predict` to calculate the conditional predictive distribution for that same set of model parameters `theta`  at the same times `t`, `np.nan` are sometimes returned. I think it might be related to issue https://github.com/dfm/celerite/issues/141, since the times where `np.nan` is returned is when the temporal gaps between data points are larger.

The things I'm mainly unsure about are:
1. The prediction is failing at the data times `t` themselves, not at some other extrapolated times `t*`. Is this a numerical issue?
2. If the prediction is failing at the data times `t` themselves, is the likelihood returned from `gp.log_likelihood` valid? 
3.  I've also noticed that while sometimes the mean of the predictive distribution returned is `np.nan`, the corresponding entries in the predictive covariance matrix are _not_ `np.nan`. Is this also a numerical issue?

Thank you!

**Comment by dfm** [comment]
Happy to help. Can you share a snippet of code that exactly reproduces the issue so that we can see what's going on?

**Comment by caseylam** [comment]
Thank you! The model I'm fitting is a bit complicated and it would be a lot longer than a snippet. Would it be okay if I email you the code/files necessary to run?

**Comment by dfm** [comment]
Please create a minimal worked example that doesn't require data or other dependencies and post that directly here. Then everyone can benefit and you might figure out the source of the issue yourself :)

**Comment by caseylam** [comment]
I used the code from https://github.com/dfm/celerite/issues/141, since it leads to the same questions, hope that is ok. 
I made some small tweaks at the end: for one calculation I included uncertainties on the data, and for one I didn't as in https://github.com/dfm/celerite/issues/141 originally.
I also added a statement to print the log likelihood.

The answers to 1. and 3. in my original post should be the same as your response to https://github.com/dfm/celerite/issues/141. A follow-up question to that, if trying to fit some data using a GP, does the predictive covariance being zero signal anything? (Is it "good" that the data is perfectly de-noised, or is it "bad" because something is being overfit?)

To check question 2. in my original post, I printed the log likelihood for this model, and it doesn't return nan. I think I still have the same question (if the prediction is failing at those times, is this log likelihood value valid? Or does the prediction have nothing to do with the calculation of the log likelihood?) 

```
import numpy as np
import celerite
from celerite import terms

class RotationTerm(terms.Term):
   parameter_names = ("log_amp", "log_timescale", "log_period", "log_factor")
   def get_real_coefficients(self, params):
       log_amp, log_timescale, log_period, log_factor = params
       f = np.exp(log_factor)
       return (
           np.exp(log_amp) * (1.0 + f) / (2.0 + f),
           np.exp(-log_timescale),
       )

   def get_complex_coefficients(self, params):
       log_amp, log_timescale, log_period, log_factor = params
       f = np.exp(log_factor)
       return (
           np.exp(log_amp) / (2.0 + f),
           0.0,
           np.exp(-log_timescale),
           2*np.pi*np.exp(-log_period),
       )

times = np.array([2455081.7836,2455756.7933,2456583.6719,2457613.6768])
residuals = np.array([-1.91,-7.12,-2.48,1.29])
B,L,Prot,C = 4.07,0.219,14.69,0.006

kernel = terms.TermSum(RotationTerm(log_amp=np.log(B),\
                                       log_timescale=np.log(L),\
                                       log_period=np.log(Prot),\
                                       log_factor=np.log(C)))

gp = celerite.GP(kernel, mean=0.0)

# No uncertainties (as originally posted in issue 141)                                                                               
gp.compute(times)
gpmodel_mu,gpmodel_cov = gp.predict(residuals, times, return_cov=True)
# gpmodel_mu returns nans while gpmodel_cov returns zeros,                                                                           
#     for the reasons outlined in issue 141                                                                                          
#     (perfectly denoised b/c gpmodel_cov = 0)                                                                                       
print(gpmodel_mu)
print(gpmodel_cov)
print(gp.log_likelihood(residuals))

# Include uncertainties                                                                                                              
gp.compute(times, [0.1, 0.1, 0.1, 0.1])
gpmodel_mu,gpmodel_cov = gp.predict(residuals, times, return_cov=True)
# gpmodel_real returns nans while gpmodel_var returns zeros,                                                                         
#     except along the diagonal (b/c of the data uncertainties)                                                                      
#     (perfectly denoised since the off-diagonals are zero)                                                                          
print(gpmodel_mu)
print(gpmodel_cov)
print(gp.log_likelihood(residuals))
```

Running this returns:
```
[-1.91   nan   nan   nan]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-14.119035217722784
[-1.90531863         nan         nan         nan]
[[0.00997549 0.         0.         0.        ]
 [0.         0.00997549 0.         0.        ]
 [0.         0.         0.00997549 0.        ]
 [0.         0.         0.         0.00997549]]
-14.105227521415538
```

**Comment by dfm** [comment]
Is this really the cadence of your observations? If so, then (as in #141) the main issue is a conceptual one. It doesn't really make sense to use a GP with all time scales <1 day and a cadence of many hundreds of days. In this case, the model is *identical* to a white noise model since the correlation lengths are << the cadence. You won't be able to fit the parameters of the model and you're not going to get any information from including a model for the correlated noise.

> The answers to 1. and 3. in my original post should be the same as your response to #141. A follow-up question to that, if trying to fit some data using a GP, does the predictive covariance being zero signal anything? (Is it "good" that the data is perfectly de-noised, or is it "bad" because something is being overfit?)

It's not good or bad, it's just a *fact* based on the model that you've chosen and the character of your data. The data points are too far apart to share any correlation information so the GP's predictive covariance will always be zero (or white in the case that you have observational uncertainty). It's a lost cause to try to fit a GP to these data :D 

> To check question 2. in my original post, I printed the log likelihood for this model, and it doesn't return nan. I think I still have the same question (if the prediction is failing at those times, is this log likelihood value valid? Or does the prediction have nothing to do with the calculation of the log likelihood?)

The log likelihood value is just fine, but it's not going to be *useful* really if you want to fit the parameters of the GP for all the reasons described above.

**The bug**: All the above being said, the fact that the `mu` is `nan` in these cases is caused by the fact that our fast algorithm for computing the mean seems to be numerically unstable for such an ill-conditioned problem. You have two options here (because I'd say that this is a low priority issue):

1. Use the even faster method to compute the predictions at your observation times:

```python
mu, cov = gp.predict(residuals, return_cov=True)  # note: no times, the prediction will be evaluated at the observations
```

2. Compute the prediction yourself (the slow way):

```python
mu = gp.kernel.get_value(times[None, :] - times[:, None]) @ gp.apply_inverse(residuals)
```

**Comment by caseylam** [comment]
> Is this really the cadence of your observations? If so, then (as in #141) the main issue is a conceptual one. It doesn't really make sense to use a GP with all time scales <1 day and a cadence of many hundreds of days. In this case, the model is identical to a white noise model since the correlation lengths are << the cadence. You won't be able to fit the parameters of the model and you're not going to get any information from including a model for the correlated noise.

No, it's not really the cadence of my data. Sorry, maybe I should have explained what I was trying to do in my original post.

I'm trying to fit multi-year ground-based lightcurve data with a photometric microlensing model. There's correlated noise in the observations, which is why I'm trying to include a GP in the model fit. The kernel is a Matern 3/2 + SHO (with the SHO motivated by astroseismic work, and the Matern 3/2 to capture non-smooth variation). I don't actually care about the parameters of the GP returned, in the sense of I'm not trying to interpret the values of the parameters themselves because I don't think the kernel I'm using is actually what's in the data (like Section 6.2 of the celerite paper). 

Below are histograms of the observational cadence of two lightcurves I'm looking at. The x-axis (`delta t`) is the time between two data points. The `delta t` span a large range (~10<sup>-2</sup> days on the very short end, because 10-30 observations are taken each night, separated by < 1 hour; 10<sup>0</sup> days on the middle range because you can observe nightly; 10<sup>2</sup> days on the long range for the ~3 months of the year the Bulge is not visible from Earth, so this is the difference between the last night of a season and the first night of the subsequent season). The data points at which the GP model prediction fails is the blue colored bars in the histogram (labelled "bad").

The GP parameters in the kernel I am fitting are log(sigma), rho, log(omega<sub>0</sub><sup>4</sup> S<sub>0</sub>), and log(omega<sub>0</sub>). The Q term for the SHO has been fixed to 1/sqrt(2). The best-fit (MAP) GP parameters that came out for these fits were:
Example 1 (top figure): 

- log(sigma) = -5.69 
- rho = 93.2 
- log(omega<sub>0</sub><sup>4</sup> S<sub>0</sub>) = -0.02
- log(omega<sub>0</sub>) = 3.27

Example 2 (bottom figure): 

- log(sigma) = -5.66 
- rho = 5.32 
- log(omega<sub>0</sub><sup>4</sup> S<sub>0</sub>) = 14.61
- log(omega<sub>0</sub>) = 8.21

So there are two timescales relevant, rho and log(omega<sub>0</sub>)-- the latter is a frequency which I can convert into time units by 2 pi/exp[log(omega<sub>0</sub>)]. So in Example 1 (top figure) the relevant timescales are T<sub>rho</sub> = 93.2 days and T<sub>omega 0</sub> = 5.7 hours, while for Example 2 (bottom figure), T<sub>rho</sub> = 5.32 days and T<sub>omega 0</sub> = 2.5 minutes. 

Here's my interpretation of the histogram, using the timescale comparison you explained. The points at which the GP model prediction fails is the blue colored bars in the histogram (the temporally widely separated observations). For Example 1 (top figure), only the very widely separated points (i.e. the first of a season, when there is a ~3 month gap between observations) are too far apart because we have a long-timescale (~90 days) and short timescale component (~5 hours). In Example 2 though, the timescales are both short (~5 days and ~3 minutes), so then points separated by more than a day fail to have a predictive covariance. Does that make sense?

![image (2)](https://user-images.githubusercontent.com/31839166/131705026-4e97e5db-01b3-445d-951a-a8352100d8da.png)
![image (1)](https://user-images.githubusercontent.com/31839166/131705033-c68bd324-628e-4751-98a5-457ab59f1870.png)

> It's not good or bad, it's just a fact based on the model that you've chosen and the character of your data. The data points are too far apart to share any correlation information so the GP's predictive covariance will always be zero (or white in the case that you have observational uncertainty). It's a lost cause to try to fit a GP to these data :D

Ah, okay, I see. So if there are many different temporal separation scales for the data, to be able to fit a GP to the data, it is necessary to have all the data spaced more periodically? For example, for multi-night observations, combine them into a single data point? Or, is it better to add more components to the GP, so each can capture a different timescale? Or, when setting priors on the GP parameters, should they be constrained to not allow such super short timescale? Not sure if either of these are valid approaches.

> The log likelihood value is just fine, but it's not going to be useful really if you want to fit the parameters of the GP for all the reasons described above.

In the case of Example 1, where only ~10 out of ~20000 observations are widely separated, would a GP fit still be okay (in that the correlations are almost completely able to be captured)? In Example 2, where ~25% of the observations are too widely separated, that means the GP is not able to model those correlations and is becoming not useful? That is, I can interpret the log likelihood returned, but the GP is really only operating on the ~75% of the points?

**Comment by dfm** [comment]
> Ah, okay, I see. So if there are many different temporal separation scales for the data, to be able to fit a GP to the data, it is necessary to have all the data spaced more periodically? For example, for multi-night observations, combine them into a single data point? Or, is it better to add more components to the GP, so each can capture a different timescale? Or, when setting priors on the GP parameters, should they be constrained to not allow such super short timescale? Not sure if either of these are valid approaches.

No this definitely isn't the right interpretation! What you're doing currently seems sensible. The point I was making wrt to the earlier example is that if *all* of the cadences are many orders of magnitude longer than the relevant timescales in the GP model, you're not getting anything from including a GP. If your cadence spans orders of magnitude, including the relevant timescales, like this then you're fine.

In the figures that you made, are you saying that the mu prediction for the points in the blue "bad" bins were all `nan`? But the points on either side were not? Can you put together an executable snippet of code with a representative sampling that demonstrates this issue?

Either way, if the conceptual issue that I described doesn't apply, then I think you're in good shape: the log likelihood should be reliable and you can use one of the methods that I proposed above for evaluating the predictive mean.

> That is, I can interpret the log likelihood returned, but the GP is really only operating on the ~75% of the points?

This isn't the right way to think about it. It's not that the GP "isn't operating" on the other data, its just that points that are much further from their neighbors than the correlation time aren't going to inform the model very much.

**Comment by dfm** [comment]
Great - and if you replace the predict line with

```python
mag_model, mag_model_var = gp.predict(mag, return_var=True)
```

it prints

```python
Number of data points:  100
Number of nans in predict:  0
Log Likelihood :  326.4187988281948
```

as expected!

**Comment by caseylam** [comment]
Awesome. Thank you so much for your help and explanations!
