### ISSUE TITLE
`quiet` cannot be accessed when initializing a term

### ISSUE THREAD

**Issue by vandalt** [dfm/celerite#171]
Hi, 

When creating a `ComplexTerm`, I tried to set `quiet=True` to avoid having an error when the prior is computed, but I got an error raised because of the check done with `kwargs` after extracting the hyperparameters from the dictionary. I saw that there is a `kwargs.get()` to get quiet right after, but it seems it cannot be reached.

https://github.com/dfm/celerite/blob/44ea277a53e57bf2f3244fa2cd4f86d58f8d241e/celerite/modeling.py#L88-L95

I was wondering if this was expected or if `quiet` is a valid keyword argument for the `ComplexTerm` class. I'm happy to contribute a PR with the changes if this is not the expected behaviour.

Thank you :)

**Comment by dfm** [comment]
Ah - I think I understand the issue, but can you write a small snippet of example code that fails in the way you think it shouldn't? Thanks!

**Comment by vandalt** [comment]
Yes, sorry I forgot to do that when opening the issue. Here's an example kernel that fails because it has non-finite log_prior value, because `ComplexTerm` checks for `self.log_a + self.log_c < self.log_b + self.log_d` in its `log_prior()`:

```python
from celerite import terms

# This gives `ValueError: non-finite log prior value`
kernel = terms.ComplexTerm(log_a=1.0, log_b=2.0, log_c=1.0, log_d=1.0)
```

And here is an example of what I'm trying to do to work around that:
```python
from celerite import terms

# This gives `ValueError: unrecognized parameter(s) '['quiet']'` on line 89 of modeling.py
kernel = terms.ComplexTerm(
    log_a=1.0, log_b=2.0, log_c=1.0, log_d=1.0, quiet=True
)
```

My use case is that I'm [trying to implement a Matern 3/2 celerite kernel in RadVel](https://github.com/California-Planet-Search/radvel/pull/358), and the GP API stores the coefficients in RadVel directly, so I'm trying to write the matern kernel with a complex term instead of the `Matern32Term`, to keep the RadVel API as generic as possible.

Thanks!

**Comment by dfm** [comment]
Good - so to fix that, I agree that the `quiet = kwargs.get("quiet", False)` should be changed to `quiet = kwargs.pop("quiet", False)` and moved to the top of that function. In the meantime, you could do something like the following to catch it manually:

```python
try:
    kernel = terms.ComplexTerm(log_a=1.0, log_b=2.0, log_c=1.0, log_d=1.0)
except ValueError:
    return -np.inf
```

Alternatively, you could write your own term that doesn't include this prior constraint:

```python
class RadVelTerm(celerite.terms.ComplexTerm):
    def log_prior(self):
        return celerite.terms.Term.log_prior(self)
```

But, I have some questions. In general, the SHO and Matern terms shouldn't ever hit this, I don't think, so I worry that there might be other issues at play here.

**Comment by vandalt** [comment]
Here's a short example with a celerite Matern 3/2 term and complex term that aims to manually replicate the Matern term:

```python
from celerite import terms
import numpy as np

# Matern parameters
eps = 0.01
sigma = 2.0
rho =  0.1

# Matern parameter -> complex coefficients
w0 = np.sqrt(3.0) / rho
S0 = sigma ** 2 / w0
complex_coeffs = w0*S0, w0*w0*S0/eps, w0, eps
log_a,log_b,log_c,log_d = np.log(complex_coeffs)

# Matern term (works)
matern_term = terms.Matern32Term(log_sigma=np.log(sigma), log_rho=np.log(rho), eps=eps)

# Custom complex term to bypass prior check
class RadVelTerm(terms.ComplexTerm):
    def log_prior(self):
        return terms.Term.log_prior(self)

# Define custom term (works
rad_term = RadVelTerm(*np.log(complex_coeffs))

# Print matern and custom terms complex coefficients
print("Matern term", matern_term.get_complex_coefficients(np.log((sigma, rho))))
print("Radvel term", rad_term.get_complex_coefficients(np.log(complex_coeffs)))
print("Prior condition that returns -inf: ", log_a + log_c < log_b + log_d)

# Complex term (fails with ValueError)
terms.ComplexTerm(*np.log(complex_coeffs))
```

I used the custom `RadVelTerm` suggested above to compare with the `Matern32Term`. They do seem to have the same coefficients.

**Comment by dfm** [comment]
I see. The condition that you're hitting is actually that `log_a + log_c == log_b + log_d` to machine precision, as it should for any SHO term (of which the Matern-3/2 is one). Personally, I'd recommend *always* using an SHO or Matern directly instead of a Complex (since these will generally have unphysical behavior), because then you wouldn't need to do any prior check and wouldn't hit this issue. If you really adamantly want to use the Complex term directly, you should probably implement a custom prior that allows `log_a + log_c == log_b + log_d` within some tolerance, but I don't think this should be part of `celerite` itself!

**Comment by vandalt** [comment]
>  The condition that you're hitting is actually that log_a + log_c == log_b + log_d to machine precision, as it should for any SHO term (of which the Matern-3/2 is one).

Ah, I should have checked for that sorry!

> Personally, I'd recommend always using an SHO or Matern directly instead of a Complex

Sounds good! This is what I ended up doing so I will keep it this way.

As for the `quiet` argument, should it still be made accessible in the `Model` declaration ? I'm happy to send a PR for this (but maybe you prefer to add it directly given that it's a small fix ?).

Thank you!

**Comment by dfm** [comment]
> As for the quiet argument, should it still be made accessible in the Model declaration ? I'm happy to send a PR for this (but maybe you prefer to add it directly given that it's a small fix ?).

Yes - that would be awesome and I'd be very happy to merge such a PR. Thank you!!
