### ISSUE TITLE
uncertainty of  fitting

### ISSUE THREAD

**Issue by Lace-t** [dfm/celerite#174]
Hi! Can Celerite derive the uncertainty of fitting?

**Comment by dfm** [comment]
It sure can. Check out this tutorial, for example: https://celerite.readthedocs.io/en/stable/tutorials/modeling/

**Comment by Lace-t** [comment]
Sorry, I may not explain my question well. I mean can I get the uncertainty of the parameters of a kernel after fitting?

**Comment by Lace-t** [comment]
I read the tutorial again.  I think I can get the distributions of the kernel parameters by MCMC. Thank you for your help!

**Comment by dfm** [comment]
Excellent - happy to help!
