### ISSUE TITLE
Shouldn't ModelSet implement get_value?

### ISSUE THREAD

**Issue by andresgur** [dfm/celerite#199]
Hi,

I know this package has (probably) been discontinued but I can't be bothered to migrate at the moment... 
If feels to me that ModelSet class is lacking the get_value function which should look something like this:
```
def get_value(self, x):

return np.sum(m.get_value(x) for m in self.models.values())
```
      
To reproduce the error something like this:
      
```
mean_model_list = [("constant", ConstantModel(value=1)), ("constant2", ConstantModel(value=1))]
meanModel = ModelSet(mean_model_list)
x = np.arange(100)
y = np.random.normal(size=100)
kernel = terms.RealTerm(log_a=np.log(np.var(y)), log_c=-np.log(10.0))
gp = celerite.GP(kernel, mean=meanModel, fit_mean=True)
gp.compute(x)
print("Initial log likelihood: {0}".format(gp.log_likelihood(y)))
```
Which gives:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/tmp/ipykernel_82289/1739930469.py in <module>
      7 
      8 gp.compute(x)
----> 9 print("Initial log likelihood: {0}".format(gp.log_likelihood(y)))

~/anaconda3/lib/python3.9/site-packages/celerite/celerite.py in log_likelihood(self, y, _const, quiet)
    200         """
    201         y = self._process_input(y)
--> 202         resid = y - self.mean.get_value(self._t)
    203         try:
    204             self._recompute()

~/anaconda3/lib/python3.9/site-packages/celerite/modeling.py in get_value(self, *args, **kwargs)
    103 
    104         """
--> 105         raise NotImplementedError("overloaded by subclasses")
    106 
    107     def compute_gradient(self, *args, **kwargs):

NotImplementedError: overloaded by subclasses

**Comment by dfm** [comment]
Hi - no, the `ModelSet` class is really meant to be an abstract subclass that handles the bookkeeping while the subclasses handle the actual behavior. Summing the values is certainly one kind of behavior, but it's definitely not the only choice. For example, the base `GP` object is a `ModelSet` that uses all of the component models differently. If you want to create a mean model that sums several other models, you'll want to subclass `ModelSet` and implement `get_value` yourself. Hope this helps!

**Comment by andresgur** [comment]
Aaah I see, now I understand, thank you!
