### ISSUE TITLE
Simulating GP

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#25]
I'm having trouble figuring out how to simulate a GP by simulating sums of exponential processes.   Some components have a negative amplitude, like the approximate Matern 3/2 kernel, and so the square root of this would be imaginary when taking the Cholesky decomposition (i.e. the kernel is not positive definite).  This despite the fact that the summed kernel is positive definite.

**Comment by ericagol** [comment]
Perhaps this paper by Newsam & Dietrich is sufficient which computes a GP on a regularly spaced grid:  http://epubs.siam.org/doi/abs/10.1137/S1064827592240555

**Comment by dfm** [comment]
I implemented this method: https://gist.github.com/dfm/37b61ce4d814f643d1270e9129e17e83

It seems (in practice) to be correct for sums of celerite terms but I haven't actually derived a proof that these kernels will satisfy the requirements for a minimal circulant embedding. This method scales as `N log(N) K` where `K` is the number of realizations compared to `N^3+N^2 K` for the standard Cholesky method. I'd want to spend some more time convincing myself that this is all correct before including it and I still think that there _must_ be an `O(N)` method!

**Comment by dfm** [comment]
This has been solved by using the Cholesky factorization so I'm going to relabel this as a paper issue so that we remember to add a discussion there.

**Comment by dfm** [comment]
Done.
