### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by dfm** [dfm/celerite#48]
Genrp is a really stupid name. I think we should consider re-branding before publication. Let's keep track of ideas here. Here are a few to get us started:

- signpost
- signpost
- flagpole
- flagship

Riffing on "scalable/fast/flexible GP".

**Comment by ericagol** [comment]
I like flagpole & signpost, but there are already multiple github repos with that name (and it's not easily google-able).

How about

congalines = COrrelated Noise  GAussian Linear Exponential Scalable

seems a little forced...

**Comment by dfm** [comment]
I'm not too worried about googlability – I think we'll be able to get to the top of "* gaussian process" easily.

I like congalines or congaline as long as we never actually give that definition!

**Comment by ericagol** [comment]
I like conga better than congaline(s), but there are quite a few repos with that name.

**Comment by dfm** [comment]
We already have twice as many stars as the most popular one though! I think we'd be ok.

**Comment by ericagol** [comment]
I just added another star...

**Comment by dfm** [comment]
On second thought, there's a certain cultural appropriation aspect to conga that makes me uncomfortable. I think we should keep brainstorming.

**Comment by ericagol** [comment]
Good point.

RApid Correlated Likelihood Evaluation for Tortuous Transiting Exoplanets = RACLETTE

(Perhaps that's too cheesy).

-Eric

**Comment by dfm** [comment]
Groan :-)

That's another good one though!

**Comment by ericagol** [comment]
RApid Scalable Correlated ALgorithm for Likelihood In Order N = RAPSCALLION

**Comment by dfm** [comment]
Even just "scallion". I like that but it's crucial that the true meaning remain a closely guarded secret.

**Comment by dfm** [comment]
^ it's -> its

**Comment by dfm** [comment]
I like "escalade" because of this definition: https://en.wikipedia.org/wiki/Escalade

**Comment by dfm** [comment]
Or potentially even "escalate".

**Comment by dfm** [comment]
Also: celerity

**Comment by dfm** [comment]
Or "celerite". This means the speed of light in a vacuum in French!

**Comment by dfm** [comment]
OK. So I think we should go with one of these:

- scallion
- celerite

With a slight preference for the second. @ericagol: what do you think?

**Comment by ericagol** [comment]
I like celerite, but it doesn't really look right from the French perspective without the three accent aigus:  célérité.   I do like the meaning (which I think is just the same as celerity). But spell check keeps trying to change it to celerity.

I'm not a big fan of scallion, though, since it doesn't relate to the algorithm in any way (and I don't like scallions or onions - basically the only two foods I won't eat if I can help it).

So, I guess I'm leaning towards celerite, or perhaps celerity?

-Eric

**Comment by dfm** [comment]
There are already a few companies called "celerity" so I don't want to go with that. I like the version without the accents because it's really just "brand" name inspired by the French word.

**Comment by ericagol** [comment]
Then celerite it is!
