### ISSUE TITLE
Changes to make in the appendix

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#51]
1).  Equation (A2) needs to have (a_j-ib_j) multiplying the second exponential.
2).  The second sentence of 5th paragraph ("We introduced complex auxiliary vectors..."), the r_n = 1/2(u_n-iv_n) to get rid of factors of 1/2 in equations (A3), (A6) & (A7) (and the 1/2 factors need to be deleted in these three).
3).  The indexing ofr_n (and hence u_n, v_n) needs to be decreased by one to start at one rather than two, so after the definition of r_n = 1/2(u_n-iv_n) the index n should be over {2,...,N-1} and r_N = 0.  Likewise, equations (A6) & (A7) should be for n from 1 to N-1.  I'm unclear on whether the indices in the equations should be increased by one, but I think that they should.
4).  The diagonal term d in equation (A3) should probably be redefined since we are already using d_j to represent the imaginary component of the damping coefficient (i.e. the oscillation frequency).
5).  The definition of y_{ex} needs to get rid of factors of /2.

**Comment by dfm** [comment]
This is done!
