### ISSUE TITLE
Matern kernel limit

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#54]
The limit of Q=1/2 that produces the Matern kernel can be taken from the sinh/cosh side to use just the exponential kernel components which slightly speeds up the solve time.  One caveat to check is whether this is more stable.

**Comment by dfm** [comment]
I've updated the document to also derive the limit from below. We probably don't need both of these but we can edit it out later. It's probably useful to include them both for now.

I'm not really sure what tests you want to do to check the stability but I agree that it's something we should consider somehow!

**Comment by ericagol** [comment]
I don't have tests in mind, except perhaps to see what happens as f -> 0 in each case.

**Comment by dfm** [comment]
I'm going to punt on this issue for now but we can revisit it later if we need to.
