### ISSUE TITLE
Problem running transit_sample.py with import command

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#58]
When running transit_sample.py with the import command, the running hangs with no CPU activity:

>>> import transit_sample.py
Initial log-likelihood: 1620.8609237832466
Maximum log-likelihood: 1681.4668190922685
MCMC save file exists. Overwrite? (type 'yes'): yes
Running MCMC sampling...

I tried running two other ways:
1).  I copied the lines of transit_sample.py to the python prompt, and then it ran fine.  The one strange thing is that the eight threads that were spawned only took ~30% of the CPU for each thread.

2). I ran it from the shell prompt:

figures$ python transit_sample.py
Initial log-likelihood: 1620.8609237832466
Maximum log-likelihood: 1681.4668190922685
MCMC save file exists. Overwrite? (type 'yes'): yes
Running MCMC sampling...
 15%|#################7                                                                                                       | 2198/15000 [01:00<04:59, 42.71it/s]

This also runs fine, but also only gives ~30% of the CPU available for each thread.

In the import case that didn't run, the eight python threads all appeared to show up, but they only executed zero runtime, so I'm wondering if it is an issue with the multi-threading allocation?

**Comment by dfm** [comment]
How are you judging the CPU usage? When I run this on my machine it uses 100% of my machine's CPU at all times.

**Comment by ericagol** [comment]
I'm using the "Activity Monitor" app.  When I ran your asteroseismic example, there are 8 python3.5 processes running at 90% of CPU (which I think means 90% of the CPU available to each thread).

When I ran the transit_sample.py, it seems to be running python, not python3.5, and only ~30% is allocated to each thread.

**Comment by dfm** [comment]
There isn't really any reason why these should be running differently! What about if you do `python3.5 transit_sample.py` or something?

**Comment by ericagol** [comment]
It still only gives me ~30% of CPU per thread!  Weird...

**Comment by dfm** [comment]
Hm... not too sure what's going on but it's probably just the overhead of how the `multiprocessing` module in Python works. I wouldn't sweat it much - looks like it's still running pretty fast for you!
