### ISSUE TITLE
Time scaling with J for Julia version of celerite

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#59]
I looked at the J-scaling of the
 Julia version, and the NR band-diagonal
solver scales like J^3 for large J;  clearly not optimal!   This plot is for N = 1024 data points, and can be found in time_julia_nexp.jl

![nr_solver_time](https://cloud.githubusercontent.com/assets/243664/22856290/312c8588-f043-11e6-9af9-fcacb00e2bee.png)

Need look into optimized band-diagonal solvers.

**Comment by dfm** [comment]
Brutal! I feel like this must have something to do with memory management because the algorithm shouldn't scale that poorly!

For optimized algorithms, take a look at: [this](http://docs.julialang.org/en/stable/stdlib/linalg/#Base.LinAlg.LAPACK.gbtrf!). The storage is similar to what you're already using but it'll need some extra workspace (there's no "al" matrix) so you'll have to resize.

**Comment by dfm** [comment]
I've added [some more complete benchmark tests](https://github.com/dfm/celerite/tree/master/examples/benchmark) to the repo using the Python bindings. 

In the following plot, solid lines show the version of the code with LAPACK bindings and the dashed lines use the numerical recipes implementation. It does look like the numerical recipes implementation scales more like J^3 at large J and the break-even point seems to be somewhere around J=8 for all N. I find the same behavior when I run on a linux machine.

![benchmark_darwin](https://cloud.githubusercontent.com/assets/350282/22858449/d78d92b2-f072-11e6-8c84-abe9fdcee4a8.png)

**Comment by ericagol** [comment]
I'm having trouble getting gbtrf! to work.  There is a matrix type called "StridedMatrix" required for input to LAPACK which I cannot find documentation on, and thus do not know how to define...

**Comment by dfm** [comment]
I think "StridedMatrix" is an abstract subclass so it should probably work with any 2D array of doubles. That being said, I don't know how to Julia. Take a look at [this page from LAPACK](http://www.netlib.org/lapack/explore-html/da/d87/dgbtrf_8f_source.html) to see the storage structure. It's the same as the numerical recipes version except you'll have `3*width + 1` rows instead of `2*width + 1`.

**Comment by dfm** [comment]
Also this stackoverflow page might help? http://stackoverflow.com/questions/34594954/how-to-call-lapack-code-cpbtrf-in-julia

**Comment by dfm** [comment]
Also this: https://github.com/JuliaMatrices/BandedMatrices.jl

**Comment by ericagol** [comment]
Thanks - that helped to see the source code!   I got this working now, and was able to run some tests.  The behavior is very strange - there is not a monotonic dependence on J (I'm actually using J to mean the bandwidth, not the number of terms).   Here is a figure which shows the dependence for N = 16,384 data points, and the power-law is my eyeball of the timing for your purple line (I doubled J to do a fair comparison).   As you can see, this behavior is quite strange.  It makes me wonder if something approximate is being done for large bandwidth.  The same exact shape occurs for other values of N, and appears to scale in proportion to N.

![time_scaling_gbtrf](https://cloud.githubusercontent.com/assets/243664/22948252/9bddd3e8-f2b2-11e6-93d0-92629a669015.png)

**Comment by dfm** [comment]
Interesting. It will _not_ be doing anything approximate for large matrices!

I got exactly the same behavior when I used OpenBLAS. Do you know what BLAS implementation was compiled into Julia? I found that using Intel's MKL library or even Apple's Accelerate framework gave consistently better results that actually scaled at J^2.

**Comment by ericagol** [comment]
So you think it may be using multi-threading for large J values?

I don't know the answer of which library is being used.

**Comment by dfm** [comment]
Looks like it's OpenBLAS: https://github.com/JuliaLang/julia#os-x

Might be! I found that on my system it was slower than the alternatives either way.

**Comment by ericagol** [comment]
Just found this:

[](http://albi3ro.github.io/M4/programming/MKL.html)

**Comment by ericagol** [comment]
Gaussian elimination scales as the bandwidth squared (J^2) times the size of the matrix (J*N), which gives the N*J^3 scaling.  So, the LAPACK algorithm is doing *better* than Gaussian elimination in computing the LU decomposition, which is impressive.
