### ISSUE TITLE
Prepare to send manuscript to collaborators and friends

### ISSUE THREAD

**Issue by dfm** [dfm/celerite#61]
Things to do before we send the manuscript around:

- [x] Give some more motivation in the intro and add some citations
- [x] Make benchmark plots comparing the different solvers and write descriptions of the tests.
- [x] Move discussion of Sturm's theorem to appendix? I'm not sure that it's worth including this in the main text because I'm not actually sure that we want to advocate for using Sturm's theorem but I do think that it's important to have some discussion of how to choose valid parameters. Perhaps this section should include the analytic results for small J.
- [x] Include examples of inference with simulated data: (a) a known celerite process where our model will be correct, and (b) another QP model where the model is wrong but we can show that we still reproduce the correct PSD and period measurement.
- [x] Finish text for examples with real data.
- [x] Add discussion of comparison to other methods including limitations of celerite. Interpretability, etc. Maybe make a benchmark plot with HODLR and CARMA included.
- [x] Cut kernel approximation section? @ericagol: I think that if we want something like this we should just include an example where we simulate data from one of these standard processes and demonstrate that we can reproduce it using celerite. I'm not a fan of fitting the autocorrelation function.
- [x] Edit and expand summary section.
- [x] ~~Add a section about parameterization and API? Optional.~~

**Comment by ericagol** [comment]
@dfm  I'm fine with cutting the kernel approximation section.  This was more useful for my own benefit to see that the damped-sinusoids could represent a range of kernel behaviors.  If we do want to simulate from a process, I would suggest the exponential-squared as this was the hardest kernel to approximate.  The exponential-sine has already been addressed in the stellar periodicity section (both are effective models for rotational variability).

**Comment by ericagol** [comment]
@dfm On second thought, if someone wants to use a specific kernel to model data with celerite, it might make sense to include these approximations as options.  I agree that it makes better sense to just use a combination of damped sinusoids from the start, but you never know what others may prefer...

**Comment by ericagol** [comment]
@dfm For instance, if someone had done an analysis with a particular kernel with another code (say george), and wanted to compare/validate the results using celerite, they may want to have access to the same kernel parameterized in the same manner as george.

**Comment by dfm** [comment]
I'm going to have to disagree with you. Unless there's a physical motivation for using something like an exponential squared then the real thing that you want to validate is that your _inferences_ don't depend on the code/kernel that you choose! I don't want to encourage people to use something like these approximations without doing more tests and having a justified motivation. If you end up with different results then it would be hard to ensure that it wasn't just caused by issues with the approximation. I do think that it's cool to demonstrate that celerite models have the support to capture structure like an exp-squared and that you can get consistent results and I think that that could go in a section called something like "kernel design" but I don't really want to include these fitting formulas in the paper. If a user really wants to use them then they can build it themselves - then at least they know what they're getting themselves into and we don't have to support it.

**Comment by ericagol** [comment]
@dfm I see your point; I'm fine with whatever you see fit.

**Comment by ericagol** [comment]
Nice job on the exponential squared example!

**Comment by dfm** [comment]
Thanks! The text needs work but I think that the example shows what we want.

**Comment by ericagol** [comment]
@dfm I moved Sturm's theorem discussion to appendix, but didn't add the J=2 formulae since they are somewhat complicated (involving the solutions of the cubic equation, and requiring the introduction of additional notation), and redundant since Sturm's theorem should work in that case as well.

**Comment by dfm** [comment]
Thanks!
