### ISSUE TITLE
Terminology for each complex exponential term

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#62]
- [x] Rather than damped sinusoid, perhaps "damped harmonic"?
- [x] Rather than "parameterized by a mean function", perhaps "consisting of a mean function"
- [x] the simplest possible example -> a simple example
- [x] To demonstrate motivate this method -> To demonstrate this method 
- [x] After equations (17) and (34) we should perhaps remind the reader that we are assuming a mean function of zero for these examples, or we can replace y with r_theta.
- [x] Notation ambiguity alert:  in section 4, x_i refers to the solution of K^{-1} y, while in section 2 it refers to the independent variable.

**Comment by dfm** [comment]
I fixed most of these issues. For the first one, I've been referring to these as "celerite terms" instead of either of these options. I think that I'd prefer to just define "celerite term" unambiguously in Section 3 and then use that terminology throughout.

**Comment by dfm** [comment]
I fixed this everywhere except for the abstract but the abstract really needs to be totally revisted anyways.
