### ISSUE TITLE
Implement the R&P method as a special case

### ISSUE THREAD

**Issue by dfm** [dfm/celerite#69]
For a single real term, the original R&P method should be somewhat more efficient. I've been playing around with it a bit today but it's not entirely trivial (but still simple) to implement for heteroskedastic noise so I'm going to leave it for now and get back to the paper. But this might be a nice thing to implement some day!

**Comment by ericagol** [comment]
Good point;   a Tri-diagonal solver suffices?

Eric Agol
Astronomy Professor
University of Washington

**Comment by dfm** [comment]
Yeah. If you don't have white noise then you can actually just analytically compute the inverse and determinant but, when you have white noise, you'll need a tridagonal solver.

**Comment by dfm** [comment]
It would be an NxN tridiagonal solve + an NxN tridagonal matrix-vector multiply instead of a ~3*N band solve with a bandwidth of 4. The gain might not actually be huge but I'd be interested to see it. I'm not allowed to actually do it until after the paper is finished though!

**Comment by dfm** [comment]
I implemented this and find that there isn't any gain for small dataset but this settles to a speedup of nearly a factor 2 for large (N >> 1000) datasets.

**Comment by ericagol** [comment]
So that means the paper is submitted?  :)

Eric Agol
Astronomy Professor
University of Washington

**Comment by dfm** [comment]
haha. So close!
