### ISSUE TITLE
Equation (A4)

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#78]
I'm confused by equation (A4).  Equations (A2) & (A3) both give lower limits for a_j*c_j, so I don't see how these turn into an upper limit that appears in equation (A4).  In fact, if b_j*d_j >0, then the condition a_j*c_j < |b_j*d_j| will cause the \omega^2 term to be negative, which will cause the power spectrum to go negative in the limit of \omega -> \infty.

**Comment by dfm** [comment]
You're totally right. I'll look at it!

**Comment by dfm** [comment]
Yeah - it looks like the correct expression is actually just `a*c > |b*d|`, which makes a lot more sense. I don't know what I was thinking when I wrote that.

What do you think of that?

**Comment by ericagol** [comment]
That sounds correct to me:

if b*d < 0, then -b*d = |b*d|, while if b*d > 0, then b*d = |b*d|

so, if a*c > b*d & a*c > -b*d, this should satisfy a*c > |b*d| since we 
already know a*c is positive.

-Eric

**Comment by dfm** [comment]
Exactly!

**Comment by dfm** [comment]
Hilariously, I had the correct expression in [my code](https://github.com/dfm/celerite/blob/master/celerite/terms.py#L342) even though it didn't make it into the paper!

**Comment by ericagol** [comment]
That's what happened with the Mandel & Agol paper - I had the correct 
expressions in my notes, and then introduced a bunch of typos into the 
paper.
>
> Hilariously, I had the correct expression in my code 
> <https://github.com/dfm/celerite/blob/master/celerite/terms.py#L342> 
> even though it didn't make it into the paper!
>

**Comment by dfm** [comment]
I find it normally happens the other way around for me but thanks for catching this!
