### ISSUE TITLE
Comments from Jake VanderPlas

### ISSUE THREAD

**Issue by dfm** [dfm/celerite#84]
- [x] Mention N^3 in abstract
- [x] In intro: include a high-level summary of the algorithmic tricks the method depends on (e.g. band solver, extended system, etc.)
- [x] Emphasize physical interpretation more in abstract
- [x] Sect 4.2: explicit formula for the size of K_{ext}
- [x] Sect 4.2: explicit NNZ/sparsity numbers
- [x] Sect 7.3: another potential application, [Wang 2012](http://iopscience.iop.org/article/10.1088/0004-637X/756/1/67/pdf)
- [x] typography for "celerite term" vs "celerite"
- [x] Respond to email

**Comment by ericagol** [comment]
That Wang (2012) reference is cool!

The matrix size also depends on the number real coefficients (vs. complex)...  should we add this to section 4.2 as well?

**Comment by dfm** [comment]
I don't think we need to go into the details of that. I think that the numbers here give enough of a sense to see how the dimensions scale. I do discuss the fact that we treat the real terms separately below but I don't think we need to give specific numbers.
